### ISSUE TITLE
Android TV support

### ISSUE THREAD

**Issue by SteveAdams86** [FWGS/xash3d#100]
I have been trying to use xash to play half life on my nvidia sheild and its no problem to load the apk and sort out the valve folder etc to be able to launch the game, it gets very difficult to control it. 

Using it on android TV means that no touch screen is available and the nvidia sheild controller does pretty much nothing. It uses WiFi direct I believe to communicate with the console it self. I have also tried with an Xbox 360 wireless controller (with the USB wireless dongle) and that didn't work. What I do find slightly odd / ammusing is that using the media remote control which has a 4 direction d pad controller and a couple of other buttons will actually alllow me to me around. No where near enough presice enough to be able to okay properly. 

The Xbox 360 controller does actually work nativly with the sheild android TV to control it fully. While I appreciate github isn't perhaps the beat place for feature requests I would love it if next release you guys could look at adding support for game controllers

**Comment by mittorn** [comment]
Ihere is some problem in dpad support. But analog joysticks should work fine.
I have no real joysticks to debug it, but i think, improved version with fixed joysticks, gyro and even VR support will be availiable later.

**Comment by a1batross** [comment]
Proper gamepad support was added in 0.18. Xash3D still don't have LEANBACK launcher, but engine works fine with any gamepads supported by Android itself.
