### ISSUE TITLE
How to compile Xash3D under OSX?

### ISSUE THREAD

**Issue by cia48621793** [FWGS/xash3d#106]
Looks like `brew install libsdl2*` didn't worked....

**Comment by mittorn** [comment]
Try compile SDL2 separately.
FindSDL2.cmake used now, so you can easily specify path to SDL2.

**Comment by a1batross** [comment]
When I compiled it, I used libsdl2 libs from libsdl.org. 
FindSDL2.cmake easily finds it.

**Comment by MyLittleRobo** [comment]
As I remember ld on OS X does not include /usr/local/lib (where homebrew creates links) as search path by default.
Before building you may need to set DYLD_LIBRARY_PATH appropriately.

**Comment by sballu** [comment]
I've been able to see the menu with OSX 10.6.8
With minor changes and gcc 4.8 instead of gcc 4.2

Now i have to compile the games libraries and see if it works :)

**Comment by a1batross** [comment]
This is how I compiled it in VirtualBox(Mac OS X 10.11):

1. Install SDL2 libraries from libsdl.org. Placed it in Frameworks.
2. mkdir build && cmake -DXASH_SDL=yes -DXASH_VGUI=no -DXASH_X11=no -DCMAKE_OSX_ARCHITECTURES=i386 ../ && make
3. Comment out functions with errors. (It's only crashhandler) 
4. `make` again.
5. Move all dylib's, xash3d and xash3d.sh to any folder.
6. Run script. 

This version will not have VGUI support. I need to launch VM and commit fixes for CMakeLists.txt

**Comment by sballu** [comment]
I've tried with the vgui less client, and I have a display problem, maybe you will be able to give some cvar to set to avoid this problem.


[](look at the picture : http://www.hostingpics.net/viewer.php?id=206263Capturedecran20160211a060246.png)

**Comment by sballu** [comment]
You can look this picture to see the problem : [Picture](http://www.hostingpics.net/viewer.php?id=206263Capturedecran20160211a060246.png)

**Comment by fnky** [comment]
Sorry for hijacking the thread, but I seem to not be able to build, because it can't find the `pm_info.h` from hlsdk (built from `xash3d/build` relatively as mentioned by @a1batross).

Using OS X 10.11.2

**Comment by fnky** [comment]
Nevermind figured it out. Forgot to set the path for the SDK.

**Comment by fnky** [comment]
Got it compiled, and running however I can't seem to play in actual levels. I have tried running with `-dev` to enable console, and start a map (also tried `+map`) however, the log says a server is spawned, but I am still within the menu.

```
[02:43:27] Set: [1440x900]
[02:43:28] Video: Intel Iris Pro OpenGL Engine
[02:43:28] AVI: Not supported
[02:43:28] UI_SetColors: colors.lst not found
[02:43:28] UI_LoadBmpButtons: btns_main.bmp not found
2016-02-12 02:43:28.395 xash3d[96014:3089345] 02:43:28.394 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
[02:43:28] Using SDL audio driver: coreaudio @ 44100 Hz
[02:43:28] execing valve.rc
[02:43:28] execing language.cfg
[02:43:28] execing autoexec.cfg
[02:43:28] execing violence.cfg
[02:43:28] execing config.cfg
[02:43:28] execing config.cfg
[02:43:28] execing touch.cfg
[02:43:35] Dll loaded for mod Half-Life
[02:43:35] Server loaded
[02:43:35] Spawn Server: c0a0
[02:43:35] execing skill.cfg
[02:43:35] server: GAME SKILL LEVEL:1
[02:43:35] server: *Graph Loaded!
[02:43:35] SV_LoadFromFile: 0 entities inhibited
[02:43:35] server: Dead end link trainstop27
[02:43:35] Game started
[02:43:36] Keynum 1073742051 out of range
[02:43:36] Keynum 1073742051 out of range
[02:43:40] Shutting down...
[02:43:40] Shutting down audio.
```

**Comment by nekonomicon** [comment]
@fnki try comment [9fd11f107bbe11a1aa618cbc0e62b64544aaeb91](url)

**Comment by nekonomicon** [comment]
@fnky try comment 9fd11f107bbe11a1aa618cbc0e62b64544aaeb91

**Comment by sballu** [comment]
You have to compile the vgui less client library 
=> [There](https://github.com/SDLash3D/hlsdk-client)

**Comment by fnky** [comment]
Ah, thanks :-)

**Comment by Solexid** [comment]
Compile hlsdk and put hl.dll and client.dll to valve ddl folders

**Comment by mittorn** [comment]
Is client loaded?
Can you post full log?

**Comment by fnky** [comment]
At the moment I haven't gotten the vgui-less hlsdk compiled, as I have to manually change Makefiles for it to compiled correctly on OS X 10.11—Which I have successfully done with the original hlsdk, but have a few struggles with your custom ones.

**Comment by sballu** [comment]
With the vgui-less client and original server one, I have graphical bugs and low fps.
I tried with both vgui-less client and server libraries, and I can t start a map.
There is nothing in log.

**Comment by fnky** [comment]
@sballu Try start it with `-dev`

**Comment by sballu** [comment]
I started with -dev 5 ;)

**Comment by mittorn** [comment]
Did you try to load original osx client?

**Comment by a1batross** [comment]
Need to write instructions about compiling Xash3D under MacOSX and, even, add it Travis.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d/wiki/Building-and-running#cmake-recommended-for-non-windows

Just use CMake. OSX is 64 bit only now, so use a command for 64 bit systems.
