### ISSUE TITLE
Нельзя кикнуть игрока

### ISSUE THREAD

**Issue by the-swank** [FWGS/xash3d#114]
Игрока с пробелом в нике нельзя кикнуть, например kick "Player (x)" напишет в ответ как использовать команду kick, а не кикнет

**Comment by Solexid** [comment]
И такое только в rcon.значит что то с рконом

**Comment by mittorn** [comment]
неа, это не с rcon. Проблема в протоколе.

**Comment by mittorn** [comment]
можешь попытаться сделать что-то вроде kick "\"Player (x)\"" в последних билдах - может прокатит.

**Comment by a1batross** [comment]
Я так понимаю, тут как-то надо эскейпить символы. 

kick -- команда серверная, поэтому форвардится на сервер она как kick Player (x), а не как kick "Player (x)". Двойные кавычки вообще должны решать такую проблему.

**Comment by mittorn** [comment]
Нет, игрока нельзя кикнуть через rcon на данный момент

**Comment by mittorn** [comment]
Точнее можно, но только по userid

**Comment by a1batross** [comment]
Fixed in 0.19.2 by @mittorn.
