### ISSUE TITLE
(Enhancement) Adding HTML MOTD Support for Xash?

### ISSUE THREAD

**Issue by CrusoeDaWolf** [FWGS/xash3d#126]
It would be interesting to see HTML support for MOTD and would add a bit more variety and customization to multiplayer servers. c;

**Comment by mittorn** [comment]
You may use touch menu instead of MOTD for android clients.

**Comment by CrusoeDaWolf** [comment]
No, no. I mean like being able to use HTML inside motd.txt, similar to how you could use it in CS 1.6

**Comment by mittorn** [comment]
I understand, but it need some html parser and renderer. And all of them are very heavy.
Using system web browser plugins is unsafe.
Maybe, it is better to just add http links support?

**Comment by CrusoeDaWolf** [comment]
Well, since that won't work, how would I get the MOTD to show up for Android users?

**Comment by fuzun** [comment]
I think it is possible to integrate qhtm project (http://gipsysoft.com/qhtm/) to xash3d like valve did for hl2. But It is not that time to do that.

**Comment by a1batross** [comment]
@CrusoeDaWolf
MOTD is disabled for cs16-client completely.

But in HL and other mods you can just send plain text. :)

2016-04-17 15:43 GMT+03:00 fuzun <notifications@github.com>:

**Comment by CrusoeDaWolf** [comment]
Alright. But it seems like Android clients don't see the MOTD at all. Is it disabled in Android or is there something I have to do to make it show up for Android clients?

**Comment by a1batross** [comment]
In CS16Client there is a cvar "cl_hide_motd".

It's done due to incomability with touch menus and my laziness to fix it.

**Comment by CrusoeDaWolf** [comment]
Alright, and how about Half-Life?

**Comment by a1batross** [comment]
Just fill your motd txt

**Comment by CrusoeDaWolf** [comment]
Well, will it show up for Android clients however if I simply fill up motd.txt?

**Comment by a1batross** [comment]
Yes.

I connected to HL1 Xash3D server and got motd. :)

**Comment by CrusoeDaWolf** [comment]
Alright. I think this can be closed for now! Thanks c:

**Comment by a1batross** [comment]
I think it should be moved to cs16-client repo. Half-Life doesn't have HTML MOTD, while the Counter-Strike have it.

**Comment by CrusoeDaWolf** [comment]
Alright, but I have another problem not related to the MOTD. So, with the new 3366 build from moddb, the textures in Stalkyard are all missing but in the newer release from github, all the textures are there, so I think there may be a problem with the moddb release. This is on WON version of HL by the way. I can send screenshots later if you want.

**Comment by a1batross** [comment]
We are not switched to 3366 branch yet. It's on testing, because many code
was been changed by Uncle Mike and it must be properly tested and adopted
to our fork.

**Comment by CrusoeDaWolf** [comment]
Alright. I'll be using the release from here then or either build it myself for now. c:

**Comment by a1batross** [comment]
Not engine enhancement. You may write in client.dll.
