### ISSUE TITLE
Custom sprays not supported?

### ISSUE THREAD

**Issue by CrusoeDaWolf** [FWGS/xash3d#130]
I recently copied my custom spray (I used tempdecal.wad and pldecal.wad) and when I test it out on my server, I still get the default lambda spray. I have tried spraying multiple times with no effect. Does Xash not support custom sprays yet or is there an option I need to change in my server? I have mp_consistency set on 0 by the way.

**Comment by lewa-j** [comment]
Xash doesn't support custom sprays yet.

**Comment by a1batross** [comment]
As packet splitting is implemented by @mittorn, why not to fix file transfer? Custom sprays depends on it.

**Comment by mittorn** [comment]
splitting is not the reason of fragment bugs

**Comment by a1batross** [comment]
Unkle Mike is working on it for Xash3D 1.0. It will be in fork too, when Xash3D 1.0 will be released and fork will sync codebase.

**Comment by a1batross** [comment]
Resolved in new engine.
