### ISSUE TITLE
Normal Map and True color image Support? (Missing in documentation)

### ISSUE THREAD

**Issue by fuzun** [FWGS/xash3d#146]
Is normal map support for textures broken or is it partially implemented? I could not get it working.

And what about true color textures? High quality textures located in a specific folder overrides classic wad-packaged-mipmaps used in bsp and added by VHE 3.5?

**Comment by nekonomicon** [comment]
>Is normal map support for textures broken or is it partially implemented? I could not get it working.

Normal map works with paranoia custom renderer.
Use libs from XashXT or Paranoia.

**Comment by fuzun** [comment]
How can I build the libs for Android?

**Comment by a1batross** [comment]
Paranoia 2 is closed-source. 

XashXT is open-source, but didn't ported yet even to Linux.

**Comment by fuzun** [comment]
@a1batross 4096x or true color textures? 

> High quality textures located in a specific folder overrides classic wad-packaged-mipmaps used in bsp and added by VHE 3.5?

And off topic but does xash3d android project support maps as menu background?

**Comment by CrusoeDaWolf** [comment]
@fuzun Xash3D Android supports maps as backgrounds. Just make a file called 'chapterbackgrounds.txt' in valve/scripts and add the map you would want (Ex. c1a1).

**Comment by mittorn** [comment]
Use materials system and tga textures for truecolor.
Bumpmaps are not supported in engine.

**Comment by fuzun** [comment]
@mittorn Does mobile port of xash3d support the material system?
Also I have found this in gl_image.c. Is this irrelevant and used for internal process ?
`
/*
=================
R_SmoothNormals

Smoothes the given normal map
=================
*/
`

**Comment by mittorn** [comment]
Material system is supported, but it is only for loading tga replacements for map textures.

**Comment by fuzun** [comment]
@mittorn So no support for studiomodel textures?
