### ISSUE TITLE
pvs-code-clean build failing on Arch Linux

### ISSUE THREAD

**Issue by CrusoeDaWolf** [FWGS/xash3d#148]
I just tried to compile the pvs-code-clean branch on Linux but it fails at 12%. Log below.

`➜  build git:(pvs-code-clean) make
Scanning dependencies of target xashmenu
[  1%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_main.cpp.o
[  2%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touchedit.cpp.o
[  2%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_configuration.cpp.o
[  3%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_credits.cpp.o
[  4%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touchbuttons.cpp.o
[  4%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_advcontrols.cpp.o
[  5%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_multiplayer.cpp.o
[  5%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_filedialog.cpp.o
[  6%] Building CXX object mainui/CMakeFiles/xashmenu.dir/utils.cpp.o
[  7%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_langame.cpp.o
[  7%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_video.cpp.o
[  8%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_audio.cpp.o
[  9%] Building CXX object mainui/CMakeFiles/xashmenu.dir/ui_title_anim.cpp.o
[  9%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_playersetup.cpp.o
[ 10%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touch.cpp.o
[ 10%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_touchoptions.cpp.o
[ 11%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_vidoptions.cpp.o
[ 12%] Building CXX object mainui/CMakeFiles/xashmenu.dir/menu_loadgame.cpp.o
[ 12%] Building CXX object mainui/CMakeFiles/xashmenu.dir/basemenu.cpp.o
/home/sergey/Xash Test/xash3d/mainui/basemenu.cpp:72:1: error: narrowing conversion of ‘4278190080u’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
 };
 ^
/home/sergey/Xash Test/xash3d/mainui/basemenu.cpp:72:1: error: narrowing conversion of ‘4294901760u’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
/home/sergey/Xash Test/xash3d/mainui/basemenu.cpp:72:1: error: narrowing conversion of ‘4278255360u’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
/home/sergey/Xash Test/xash3d/mainui/basemenu.cpp:72:1: error: narrowing conversion of ‘4294967040u’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
/home/sergey/Xash Test/xash3d/mainui/basemenu.cpp:72:1: error: narrowing conversion of ‘4278190335u’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
/home/sergey/Xash Test/xash3d/mainui/basemenu.cpp:72:1: error: narrowing conversion of ‘4278255615u’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
/home/sergey/Xash Test/xash3d/mainui/basemenu.cpp:72:1: error: narrowing conversion of ‘4293964824u’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
/home/sergey/Xash Test/xash3d/mainui/basemenu.cpp:72:1: error: narrowing conversion of ‘4294967295u’ from ‘unsigned int’ to ‘int’ inside { } [-Wnarrowing]
make[2]: *** [mainui/CMakeFiles/xashmenu.dir/build.make:495: mainui/CMakeFiles/xashmenu.dir/basemenu.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: mainui/CMakeFiles/xashmenu.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
`

**Comment by a1batross** [comment]
As workaround, you can build engine only. 

It must be fixed, yeah.

**Comment by CrusoeDaWolf** [comment]
Building the engine only gives me this:

`➜  engine git:(master) make -f Makefile.linux XASH_VGUI=1
cc -Og -ggdb -m32 -I/usr/include/SDL2 -Icommon -I../common -I. -I../pm_shared -Iclient -I/home/sergey/Xash Test/xash3d/engine/../../xashXT/common -I/home/sergey/Xash Test/xash3d/engine/../../halflife//public -Iserver -Iclient/vgui -Icommon/sdl  -DXASH_SDL -DXASH_VGUI -fPIC -c server/sv_cmds.c -o server/sv_cmds.o -fvisibility=hidden -DGDB_BREAK
cc: error: Test/xash3d/engine/../../xashXT/common: No such file or directory
cc: error: Test/xash3d/engine/../../halflife//public: No such file or directory
make: *** [Makefile.linux:60: server/sv_cmds.o] Error 1
`

**Comment by a1batross** [comment]
Use cmake, Luke.

**Comment by nekonomicon** [comment]
You can try build with clang or old versions gcc.

**Comment by mittorn** [comment]
Remove spaces from Xash Test folder name. I'll fix it later.

**Comment by CrusoeDaWolf** [comment]
Alright.
@nekonomicon How would I build with clang?

**Comment by ryan-sg** [comment]
@CrusoeDaWolf  you should be able to define CC/CXX before you call cmake, which will cause cmake to choose the defined compiler instead.

```
$ mkdir build
$ cd build
$ CC=clang CXX=clang++ cmake ..
```

**Comment by CrusoeDaWolf** [comment]
@ryan-sg Thanks! Compiled with some warnings but it works now.

**Comment by xDShot** [comment]
Still occurs when compile with GCC 6.1, even on master branch.

**Comment by nekonomicon** [comment]
@xDShot, try build mainui with -std=c++98
