### ISSUE TITLE
Capability of handling Studiomodel limits?

### ISSUE THREAD

**Issue by fuzun** [FWGS/xash3d#151]
Defines in "hlsdk-xash3d/engine/studio.h":
```
// studio limits
#define MAXSTUDIOTRIANGLES		32768	// max triangles per model
#define MAXSTUDIOVERTS		4096	// max vertices per submodel
```

What can happen if I push these up to these and of course compiling and using a corresponding mdl : (Overflows maybe?)

```
#define MAXSTUDIOTRIANGLES		1048576	// max triangles per model
#define MAXSTUDIOVERTS		1048576	// max vertices per submodel
```

I am actually wondering what is the maximum of these limits that Xash3d can handle.

**Comment by mittorn** [comment]
XashXT and Paranoia2 can handle larger models with custom renderer.
Here is exampe of very heavy model:
http://cs-mapping.com.ua/forum/showthread.php?t=37136

**Comment by fuzun** [comment]
Its really good that it supports with a custom renderer.

> Не пытайтесь открыть эту модель нигде кроме обновленной паранои

So is not it possible to push these limits up and utilize a high poly model like that 'alyx' model without a custom renderer? Has anyone tested it yet? (I just work with bare Xash3d android project)

**Comment by mittorn** [comment]
Try code-clean branch. We have updated engine renderer and it should support really big models, it will be in master soon.
