### ISSUE TITLE
Host_InitError: can't initialize client.dll

### ISSUE THREAD

**Issue by CrusoeDaWolf** [FWGS/xash3d#158]
> =================================================================================
	Xash3D 0.98 (build 3366) started at Jul19 2016 [22:28.34]
=================================================================================
Sys_LoadLibrary: Loading xash.dll - ok
FS_Init: done
FS_LoadGameInfo( valve )
FS_Rescan( Half-Life )
Adding wadfile valve/cached.wad (2 files)
Adding wadfile valve/decals.wad (222 files)
Adding wadfile valve/fonts.wad (3 files)
Adding wadfile valve/gfx.wad (7 files)
Adding wadfile valve/halflife.wad (3116 files)
Adding wadfile valve/liquids.wad (32 files)
Adding wadfile valve/spraypaint.wad (14 files)
Adding wadfile valve/tempdecal.wad (1 files)
Adding wadfile valve/xeno.wad (264 files)
InitDecals: 222 decals
Sys_LoadLibrary: Loading wsock32.dll - ok
NET_Init()
Console initialized.
execing video.cfg
execing opengl.cfg
Sys_LoadLibrary: Loading opengl32.dll - ok
GL_CheckExtension: OpenGL Internal ProcAddress - enabled
Set: Mode 20: 16x9 [1920x1080]
VID_ChoosePFD( color 24, alpha 8, depth 32, stencil 8 )
VID_ChoosePFD: using hardware acceleration
GL PFD: color( 32-bits ) alpha( 8-bits ) Z( 24-bit )
VID_StartupGamma: restore original gamma after crash
GL_CheckExtension: OpenGL 1.1.0 - enabled
Video: GeForce GTX 960/PCIe/SSE2
GL_CheckExtension: WGL_EXT_swap_control - enabled
GL_CheckExtension: glDrawRangeElements - enabled
GL_CheckExtension: GL_ARB_multitexture - enabled
GL_CheckExtension: GL_ARB_texture_env_combine - enabled
GL_CheckExtension: GL_ARB_texture_env_dot3 - enabled
GL_CheckExtension: GL_EXT_texture3D - enabled
GL_CheckExtension: GL_SGIS_generate_mipmap - enabled
GL_CheckExtension: GL_ARB_texture_cube_map - enabled
GL_CheckExtension: GL_ARB_seamless_cube_map - enabled
GL_CheckExtension: GL_EXT_point_parameters - enabled
GL_CheckExtension: GL_ARB_texture_non_power_of_two - enabled
GL_CheckExtension: GL_ARB_texture_compression - enabled
GL_CheckExtension: GL_EXT_compiled_vertex_array - enabled
GL_CheckExtension: GL_EXT_texture_edge_clamp - enabled
GL_CheckExtension: GL_EXT_texture_filter_anisotropic - enabled
GL_CheckExtension: GL_EXT_texture_lod_bias - enabled
GL_CheckExtension: GL_ARB_texture_border_clamp - enabled
GL_CheckExtension: GL_EXT_blend_minmax - enabled
GL_CheckExtension: GL_EXT_blend_subtract - enabled
GL_CheckExtension: glStencilOpSeparate - enabled
GL_CheckExtension: GL_EXT_stencil_two_side - enabled
GL_CheckExtension: GL_ARB_vertex_buffer_object - enabled
GL_CheckExtension: GL_ARB_texture_env_add - enabled
GL_CheckExtension: GL_ARB_shader_objects - enabled
GL_CheckExtension: GL_ARB_shading_language_100 - enabled
GL_CheckExtension: GL_ARB_vertex_shader - enabled
GL_CheckExtension: GL_ARB_fragment_shader - enabled
GL_CheckExtension: GL_ARB_depth_texture - enabled
GL_CheckExtension: GL_ARB_shadow - enabled
GL_CheckExtension: GL_ARB_texture_float - enabled
GL_CheckExtension: GL_ARB_depth_buffer_float - enabled
GL_CheckExtension: GL_ARB_occlusion_query - enabled
GL_Upload: *white s&3 [1 x 1]
GL_Upload: *gray s&3 [1 x 1]
GL_Upload: *black s&3 [1 x 1]
GL_Upload: *vsdct s&3 [1 x 1]
SCR_Init()
Sys_LoadLibrary: Loading ../menu.dll - ok
Sys_LoadLibrary: Loading avifil32.dll - ok
Sys_LoadLibrary: Loading msvfw32.dll - ok
Sys_LoadLibrary: Loading msacm32.dll - ok
AVI_Initailize: done
GL_Upload: gfx/shell/min_n s&3 [19 x 19]
GL_Upload: gfx/shell/min_f s&3 [19 x 19]
GL_Upload: gfx/shell/min_d s&3 [19 x 19]
GL_Upload: gfx/shell/cls_n s&3 [19 x 19]
GL_Upload: gfx/shell/cls_f s&3 [19 x 19]
GL_Upload: gfx/shell/cls_d s&3 [19 x 19]
Sys_LoadLibrary: Loading dlls/hl.dll - ok
Sys_FreeLibrary: Unloading dlls/hl.dll
Sys_LoadLibrary: Loading dsound.dll - ok
SNDDMA_InitDirect: creating DS object - ok
DS_CreateBuffers: initialize
DS_CreateBuffers: setting EXCLUSIVE coop level - ok
DS_CreateBuffers: creating primary buffer - ok
DS_CreateBuffers: setting primary sound format - ok
DS_CreateBuffers: creating secondary buffer - ok
DS_CreateBuffers: using secondary sound buffer
Audio: DirectSound
Sys_LoadLibrary: Loading cl_dlls/client.dll - failed
DS_DestroyBuffers: shutdown
DS_DestroyBuffers: setting NORMAL coop level
DS_DestroyBuffers: stopping and releasing sound buffer
DS_DestroyBuffers: releasing primary buffer
Host_InitError: can't initialize client.dll

Log is above. I compiled my own client.dll from SDLash3D/halflife github. All I did was edit hud.cpp and view.cpp to bring back the old viewroll and view bob from the CD Retail version. Instructions from here: https://github.com/ValveSoftware/halflife/issues/1544

I'm using build 3366 from Moddb.

**Comment by nekonomicon** [comment]
This client uses vgui.so.
Try build vguiless-client from hlsdk-xash3d repo(and server too).

**Comment by a1batross** [comment]
Or just compile vgui_support.dll.
20.07.2016 10:25 пользователь "Andrey Akhmichin" <notifications@github.com>
написал:

**Comment by CrusoeDaWolf** [comment]
@a1batross I've tried using vgui.dll from the Steam version of HL and I've tried using the vgui_support.dll
Both didn't work.
As for compiling hlsdk-xash3d, it failed giving me a bunch of errors and how it couldn't find some files. :c

**Comment by mittorn** [comment]
@CrusoeDaWolf, try remove missing files from visual studio project. We do not have visual studio now to update project, We only use mingw to build it.
vgui_support is vgui dll loader. It used to remove direct engine dependency on vgui. It MUST be placed to engine root folder, that contains valve folder and vgui.dll (from laterst steam version, not old version that used by original xash3d)

**Comment by nekonomicon** [comment]
But @CrusoeDaWolf wrote about original xash3d which not used shared vgui_support.dll. %)

**Comment by mittorn** [comment]
Original xash needs obsolete vgui.dll version

**Comment by CrusoeDaWolf** [comment]
@mittorn What do you mean by obsolete vgui.dll? The one that comes bundled in with the original Xash or the one from the Steam version of HL?

**Comment by a1batross** [comment]
@CrusoeDaWolf

Valve updated VGUI1 after Linux port. So it's isn't binary compatible with
WON vgui.dll anymore.

If you want to use _original_ Uncle Mike's Xash3D -- use WON vgui.dll(it
came in 7z archive with Xash3D).
If you want to use Xash3D SDL -- use Steam latest vgui.dll.

2016-07-21 23:50 GMT+06:00 CrusoeDaWolf <notifications@github.com>:

**Comment by CrusoeDaWolf** [comment]
I fixed the problem. Closing this now.
