### ISSUE TITLE
default_fov not changing at all

### ISSUE THREAD

**Issue by CrusoeDaWolf** [FWGS/xash3d#164]
Whenever I set default_fov to 110 or some other number, it doesn't seem to take any effect at all, even after restarting a server. Any idea why? :/

**Comment by nekonomicon** [comment]
This cvar not implemented into engine and hlsdk.
You can try use XashXT client library(default_fov implemented.).
Or use r_adjust_fov {0, 1}.

**Comment by CrusoeDaWolf** [comment]
r_adjust_fov 0 makes it worse, so I'll wait the cvar to be implemented then. Thanks!

**Comment by a1batross** [comment]
r_adjust_fov is not a solution.

default_fov is works, but I don't remember in which branch it's implemented.

**Comment by CrusoeDaWolf** [comment]
pvs-code-clean maybe? I'll check it out myself later.

**Comment by a1batross** [comment]
Look for commit history. I pushed bugfix related to default_fov.

2016-08-16 20:56 GMT+06:00 CrusoeDaWolf <notifications@github.com>:

**Comment by CrusoeDaWolf** [comment]
Yep, It was pvs-code-clean. Thanks!

**Comment by mittorn** [comment]
Will be fixed in 0.19

**Comment by CrusoeDaWolf** [comment]
Apparently, disabling cl_lw seems to fix it. :/

**Comment by a1batross** [comment]
Fixed in pvs-code-clean.
