### ISSUE TITLE
Counter-Strike 1.6 support?

### ISSUE THREAD

**Issue by kuwoh** [FWGS/xash3d#167]
hello there, i try to run cs 1.6 but when i launch it it says 
Could not load client library
LoadLibrary failed for cl_dlls/client.dll:126
LoadLibraryExt: could not find client.dll!

also it doesnt seem to load maps too

**Comment by Xeddius** [comment]
Can you provide any more details?
1. Did you copy an "unpacked" cstrike and valve folder wherever you're trying to run it?
2. Do you own a legitimate copy?
3. What system, os version, etc, are you attempting to run the engine on?
4. What version of Xash are you running?

Without more details, we can't help, if this is a legitimate bug then we can work on it, but without further info, this could also be user error.
Please provide more information.

**Comment by CrusoeDaWolf** [comment]
You can't play CS1.6 itself as it has an encrypted client.dll I believe. You can only run a server.

If you want to run CS, use CS1.3.

**Comment by Xeddius** [comment]
@CrusoeDaWolf is there no possibility of reverse engineering the client.dll and client.so files? I'm willing to be a guinea pig.

Systems:
--Linux
----Arch
----Ubuntu 16.04
----Ubuntu 14.04
----Linux Mint 17.3 & 18

--Windows
----Windows 7
----Windows XP

--Android
----Marshmallow 6.0.1
----Lollipop 5.0

And enough experience to compile code from source, light hex editing, bash script, batch script, php, and python.

**Comment by CrusoeDaWolf** [comment]
There is an Android port of it. You can find it on moddb or here:
https://github.com/FWGS/cs16-client

**Comment by a1batross** [comment]
Original client.dll uses features, that not implemented in Xash3D.

That's why cs16-client exists.
22.08.2016 1:33 пользователь "CrusoeDaWolf" <notifications@github.com>
написал:

**Comment by a1batross** [comment]
You can also look to `vinterface` branch. I tried to implement missing features in engine, but... it's segfaults. :)

**Comment by kuwoh** [comment]
is there cs16 client for windows?
and i do own a legitimate steam copy
also i am running windows

**Comment by CrusoeDaWolf** [comment]
No. Just use CS1.3 + original Xash3D from moddb (3366).

I may run a dedicated server, assuming I can find out how to specify the port in Xash

**Comment by kuwoh** [comment]
but can you multiplayer with android xash

**Comment by CrusoeDaWolf** [comment]
With Xash3D SDL, yes. With the original one from moddb, I'm not sure.

Either way, my server is still running. Just grab Xash from moddb, grab a CS1.3 installer, and enjoy. xP

**Comment by ryan-sg** [comment]
@crusoedawolf  you confused me a bit!  i am running on a non-windows platform and at first glance tricked me into downloading csv13full.exe, extracting and trying that instead.  only then did i realize wait -- the associated cs xash project is cs16, not a cs13-client, so that won't work at all!

Do you mostly mean you can't use sdl xash3d + their cs16-client library to join existing windows servers?  Just wondering for clarity's sake and future readers.  (But conversely, using a stock cstrike windows install with xash3d does work?)

FWIW -- i synced cs16-client to master and rebuilt last night, i can enter xash3d cstrike servers but can't move around, weapons don't show.  i can crouch, but then usually after 10-15 seconds xash3d segfaults.  I am sure this is likely a known issue, perhaps more 32bit code not playing nice when compiled 64-bit. (Running on OpenBSD/amd64, so 64-bit is a must).   Things seem to always be improving though!

**Comment by a1batross** [comment]
You can fix 64-bit in cs16-client by yourself.

cs16-client is intended to run only on Android. Yes,  it builds for Linux
32 on my workstation, but it's more "private" support than "public".

**Comment by CrusoeDaWolf** [comment]
@ryan-sg You can't play CS1.6 on Xash at all. Only 1.3 and earlier work in Xash.

**Comment by ryan-sg** [comment]
okay, is there any known cs-client tree in the works for cs 1.3?   how does regamelite fit into the CS puzzle?  thanks @a1batross and @crusoedawolf for clarification!

**Comment by CrusoeDaWolf** [comment]
@ryan-sg As a1batross said, cs16-clean is only for Android. If you want to play CS on Xash3D on PC, get CS1.3 or earlier. I'm not sure about ReGameLite. I can test it out on CS1.3 if you would like.

**Comment by nekonomicon** [comment]
@CrusoeDaWolf, CS1.3 not works on OpenBSD amd64.
You can build cs16-client for any platform, but without mouse look support.

**Comment by CrusoeDaWolf** [comment]
@nekonomicon I know CS1.3 does not work on OpenBSD, Mac, Linux, etc. as it uses DLLs.

**Comment by mittorn** [comment]
@CrusoeDaWolf, there is DLL loader and it is able to run cs 1.3 client, i've specially worked on it's support.
But it may conflict with mesa driver.

**Comment by CrusoeDaWolf** [comment]
@mittorn
Ah, alright cool.

Unrelated, but in Opposing Force on Linux, there seems to be missing textures in maps like training and such. Not sure if it has been patched yet, but can you take a look at it?

**Comment by a1batross** [comment]
This was fixed in latest commits. Rebuild Xash3D from master branch.

Also, you can workaround this by renaming OPFOR.WAD to opfor.wad.

**Comment by Snow344** [comment]
```As a1batross said, cs16-clean is only for Android. If you want to play CS on Xash3D on PC, get CS1.3 or earlier. I'm not sure about ReGameLite. I can test it out on CS1.3 if you would like.```
So, will this work fine with Xash in Windows? 
https://www.moddb.com/mods/counter-strike/downloads/counter-strike-13

**Comment by mittorn** [comment]
CS 1.3 will work, but note that it is not fully compatible with cs1.6 server. We do not recommend use it to play on 1.6 servers.

**Comment by Snow344** [comment]
> 
> 
> CS 1.3 will work, but note that it is not fully compatible with cs1.6 server. We do not recommend use it to play on 1.6 servers.
> You may run cs 1.3 server with different gamedir to not confuse players with non-working menus ang glitching prediction

Gotcha, thanks!
