### ISSUE TITLE
Зависание от precache

### ISSUE THREAD

**Issue by lewa-j** [FWGS/xash3d#168]
Если ввести в консоль команду precache когда ты подключён, в консоль выведёт "begin is not valid from the console" и после закрытия консоли, игра зависает. Просто перестаёт отвечать, без краша.
PS: Знаю что игрок не должен вводить эту команду, но поведение непонятное, надо исправлять.

**Comment by a1batross** [comment]
>is not valid from the console

**Comment by mittorn** [comment]
Вроде исправлено. Проверь снова

**Comment by mittorn** [comment]
Баг с прекэшем имеет место. Точнее, это баг отрисовки прогрессбара.
