### ISSUE TITLE
In-game subtitle text box support

### ISSUE THREAD

**Issue by hathlife** [FWGS/xash3d#171]
In Source engine there's a in-game subtitle text box feature,which let non-english users also understand the plot when there's english voice only.However in Goldsrc there was not.So it's possible to integrate a subtitle text box in Xash ,loaded third-party subtitle text?

**Comment by CrusoeDaWolf** [comment]
http://www.moddb.com/mods/half-life-subtitles-mod/downloads

There is a mod for that. Choose the language you want (If it's there) and run it as a mod.

**Comment by fuzun** [comment]
Do you want engine level subtitle support?

**Comment by a1batross** [comment]
Subtitles mod uses VGUI to draw subtitle box. (And hzqst's mod uses VGUI2, because full Unicode support). 
They are not available for ARM architecture. To get subtitles working one should reimplement VGUI or rewrite Subtitles MOD. Both ways are require time and hard work. :(

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d/issues/177

Moved to.
