### ISSUE TITLE
amxmodx crashing

### ISSUE THREAD

**Issue by MisterPix** [FWGS/xash3d#176]
Hello,

I have ubuntu 14.04 server with xashds 0.18 counterstrike 1.6

When amxmodx is enabled and someone tries to join server, than server crashes with this message:
/usr/games/xashds: line 34: 17430 Segmentation fault      (core dumped) ${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} $@

Also i see this:
[AMXX] Loaded 0 admins from file
[17:46:40]  20 player server started
[17:46:40]  Adding your server to master server list
[17:46:40]  couldn't exec /amxx.cfg
[17:46:40]  couldn't exec /sql.cfg
[17:46:40]  couldn't exec /custommenuitems.cfg

**Comment by mittorn** [comment]
It is metamod problem:
https://github.com/mittorn/metamod-p/commit/8f56fd172045cbd63ce0a11df5532cc75e9d1e45#diff-cd2425d354ad61aef5f2e65e07f0fc31L181
This fixes it

**Comment by MisterPix** [comment]
I have downloaded the source and did make than make install
Put the metamod.so in right location and now i get: undefined symbol: __gxx_personality_v0

Do you maybe have the good file for me?

**Comment by mittorn** [comment]
try replace gcc with g++

**Comment by HKSKiller** [comment]
how?
