### ISSUE TITLE
Improving "Mute when inactive" option

### ISSUE THREAD

**Issue by UCyborg** [FWGS/xash3d#180]
About the code that mutes the audio that currently just sets volumes to zero, it might be a better idea to call SDL_PauseAudio in response to window focus gained/lost events.

Also, putting an extra check whether the game is active or not and whether user wants it to be quiet when the focus is lost (cvar snd_mute_losefocus) would need to be put at the beginning of S_UpdateChannels function.

This may need some more code to make it perfect, but making it like this, if I understand correctly, would be the closest to the behavior of the original DirectSound based code.

**Comment by mittorn** [comment]
You late, it done two days ago
https://github.com/FWGS/xash3d/commit/664ba036a5bbd9d4e9ca5e1cfd5e5a70325c2c6a

**Comment by UCyborg** [comment]
Oops, missed it. Then this can be closed. Just in case you missed it, can you take another look at #80?
