### ISSUE TITLE
Overbrights

### ISSUE THREAD

**Issue by Matthaiks** [FWGS/xash3d#181]
Could you add gl_overbright to the engine?

Some info:
https://www.vogons.org/viewtopic.php?f=5&t=47313

**Comment by mittorn** [comment]
We don't know how it really works. Try increase texgamma in opengl.cfg for similar effect, but it decreases texture quality as it is software gamma implementation.

**Comment by mittorn** [comment]
Overbrights can be easily implemented in opengl core profile

**Comment by ShaunNoWay** [comment]
What is OpenGL core profile? I've been trying to implement overbrights into Xash3D but with no luck.

**Comment by a1batross** [comment]
Implemented. 
Included in next 0.19 release.

**Comment by Matthaiks** [comment]
Thanks!

**Comment by a1batross** [comment]
@Matthaiks there is also a cvar r_lighting_modulate. It may help you to achieve overoverbrights. :)
