### ISSUE TITLE
Minimalist SDK

### ISSUE THREAD

**Issue by cia48621793** [FWGS/xash3d#182]
HLSDK-Xash3D is still too fat for me. I'm bothered to delete all the stuff I don't need.
CS-client mod seems promising to skin (With nice grouping) but there were ring-dependency code-wise.

**Comment by mittorn** [comment]
You need multiplayer-only sdk? I think, removing some entitu sources would be enough.
If you need really small SDK, try QuakeRemake.
Studio render may be easily ported to other mods by copy-paste.

**Comment by mittorn** [comment]
Cs16client is client only. Do not use it's server implementation, it is only for client weapons.

**Comment by a1batross** [comment]
Use headers from Xash3D repository and make your own SDK. You can even make
HL on another language.

It's super-mega-minimalistic SDK.
09.09.2016 0:43 пользователь "Steve Fan" <notifications@github.com> написал:

**Comment by cia48621793** [comment]
＠a1batross Could you provide some details of which headers should be copied. I'm trying to merge Xash3D with Mono...

**Comment by a1batross** [comment]
Constans, data structures and interfaces are defined in common/, engine/,
pm_shared/ directories.
09.09.2016 13:49 пользователь "Steve Fan" <notifications@github.com>
написал:

**Comment by mittorn** [comment]
engine/eiface.h contains main engine interface

**Comment by a1batross** [comment]
https://github.com/FWGS/stubserver

@mittorn implemented it. I think, it's a good start on developing your own game from scratch.
