### ISSUE TITLE
pfnServerPrint работает не правильно.

### ISSUE THREAD

**Issue by THE-Swank** [FWGS/xash3d#183]
Отправляет все что пишется в серверную консоль всем игрокам.
То есть все игроки например видят мои данные когда я авторизируюсь в amxx и кучу другой инфы которая должна быть только в консоле.

**Comment by a1batross** [comment]
**ReHLDS**: https://github.com/dreamstalker/rehlds/blob/fe9bfbbc7070706b8b3e7c3e451d25952d9bece6/rehlds/engine/pr_cmds.cpp#L216

**Xash3D**: https://github.com/FWGS/xash3d/blob/57f123bea93ee5c838a170e50b4490a1db6a89e9/engine/server/sv_game.c#L3293

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d/commit/e12d46ceb1b6fc2142424f261b8c0cbfa8851ec3

Fixed.
