### ISSUE TITLE
CVar "fps_max" not working correctly

### ISSUE THREAD

**Issue by Ghost90** [FWGS/xash3d#195]
If you set CVar to 120, 121, 122, 123, 124 fps will be 111, and if you set to 125, fps will be 111 + 4 (124-120=4).

**Comment by a1batross** [comment]
sleeptime 0. But here is another bug, which don't allow zero sleep time
values.
13.10.2016 15:13 пользователь "Beqa" <notifications@github.com> написал:

**Comment by Ghost90** [comment]
English please!

**Comment by a1batross** [comment]
@Ghost90 I know that mine English isn't so good, because I'm not a native speaker. But what you don't understood?

**Comment by Solexid** [comment]
@a1batross he from Georgia.Короче он просто выебывается.

**Comment by nekonomicon** [comment]
@a1batross, translate it:
>пользователь "Beqa" <notifications@github.com> написал:

*rofl*

**Comment by a1batross** [comment]
@nekonomicon xD
Well, I just removed this line. 

@Ghost90 don't worry, it means nothing :)

**Comment by Ghost90** [comment]
OMG, These guys are actually Non-Humans.
I wanted to tell you guys an issue, but look what you wrote.

**Comment by ShaunNoWay** [comment]
Don't be so rude. Not everyone speaks perfect English.

The issue should be fixed by setting the "sleeptime" cvar to 0, but apparently there's a bug that won't allow the it to be set at a value of 0.

**Comment by a1batross** [comment]
BTW, this is fixed in the code
https://github.com/FWGS/xash3d/commit/9b54949c6ed9a64ad8b15cc0ce6a7c674ee57b41
.


So...I think, it must be closed. Only if your issue is not about
developers' knowledge of English.



2016-10-27 19:11 GMT+03:00 ShaunNoWay <notifications@github.com>:
