### ISSUE TITLE
Демо в сингле

### ISSUE THREAD

**Issue by vlad54rus** [FWGS/xash3d#197]
Когда я запускаю запись демо в синглплеере, у игрока пропадают патроны ко всему оружию.

**Comment by mittorn** [comment]
Seems to be related to fullupdate. Demo  needs fullupdate in start to record correct hud state. Using fullupdate makes some hud items 0.

**Comment by a1batross** [comment]
Баг серверки. Исправлено в hlsdk-xash3d.
