### ISSUE TITLE
sv_downloadurl problem

### ISSUE THREAD

**Issue by HKSKiller** [FWGS/xash3d#198]
Hi, 

I have problem about my sv_downloadurl. I have created a website using IIS8 for fastdl the custom maps for my server. I can access my IIS websites from public by using IP only not using domain. The path is correctly set in the virtual directory and i can download the maps from my website if using Internet Browser eg: Chrome and IE. 

I also edited my server.cfg file and put my website url for sv_downloadurl. 

sv_downloadurl "http://mywebsiteIP/hldm/valve/"
sv_allowdownload 1
sv_allowupload 1

But the problem is, whenever i run the dedicated server on my pc and i try to join the internet game from another game folder that doenst have the custom map yet i still got error Map Design Error : Mod_ForName : xxxxxxx.bsp couldnt load. 

Can someone help me on how to solve this?

**Comment by nekonomicon** [comment]
Use **sv_allow_download** cvar instead of **sv_allowdownload**(It's typo into xash3d).
**sv_allowupload** not implemented.

**Comment by HKSKiller** [comment]
> Use sv_allow_download cvar instead of sv_allowdownload(It's typo into xash3d).
sv_allowupload not implemented.

OMG. Finally it works! I have been googling for hours to solve about it. I didn't notice the cvar is different from steam version of half-life. thank you so much sir.
