### ISSUE TITLE
Buggy studio shadows in latest build

### ISSUE THREAD

**Issue by ShaunNoWay** [FWGS/xash3d#199]
Seems the latest update to studiomodel renderer has messed up studiomodel shadows. They worked fine in the old Win32 release.

![reg](https://cloud.githubusercontent.com/assets/14033754/19780038/acf259ae-9c51-11e6-8b66-c08beecdc84d.png)
![bug](https://cloud.githubusercontent.com/assets/14033754/19780047/b3bc0bb8-9c51-11e6-94fe-19e0cf8aeb03.png)

**Comment by mittorn** [comment]
try gl_studio_drawelements 0

**Comment by a1batross** [comment]
I can't get it working even if r_studio_drawelements was set to 0. =/

**Comment by ShaunNoWay** [comment]
r_studio_drawelements changes it, but they're still broken.
![t0a0d_0002](https://cloud.githubusercontent.com/assets/14033754/19784736/e1b039a0-9c64-11e6-9d46-f5c055439858.png)

Also, when capturing the glitch with the "snapshot" command, the parts where the shadows are drawn are semi-transperant in the BMP. Very odd. They don't appear like that in normal gameplay.

**Comment by TacoDeBoss** [comment]
Sorry to bump the thread, but I wasn't even aware the engine had shadows. How are you supposed to enable them in the first place?

**Comment by ShaunNoWay** [comment]
@TacoDeBoss Make the if statement in the GL_StudioDrawShadow function return true, or just remove the if statement completely. https://github.com/FWGS/xash3d/blob/master/engine/client/gl_studio.c#L3022

**Comment by TacoDeBoss** [comment]
@ShaunNoWay Must only work in Windows, or else I'm screwing it up. Messed with that every way I could and it made no difference.

**Comment by ShaunNoWay** [comment]
@TacoDeBoss May I ask what you did? Just changing the line to "if( true )" does it for me.

**Comment by ShaunNoWay** [comment]
Of course, shadows are super bugged right now and very hard to see unless under specific circumstances.
![bug](https://cloud.githubusercontent.com/assets/14033754/20244267/51988250-a948-11e6-853c-7a1848a2e8d6.png)

Try settting r_studio_drawelements to 0 and see if that makes a difference.
![range](https://cloud.githubusercontent.com/assets/14033754/20244249/3acfc696-a948-11e6-9d36-09c2812bf99f.png)

**Comment by TacoDeBoss** [comment]
![c1a0d_0001](https://cloud.githubusercontent.com/assets/2870898/20249055/ade3991e-a9b6-11e6-88de-1a8fd594dfd2.png)

@ShaunNoWay Yeah, I did just that with no luck. Mine is a slightly older build because I'm having trouble compiling the newest version on Linux.

**Comment by mittorn** [comment]
It is not fixed yet, update will not help. It is because we replaced old glBegin/glEnd studio renderer but new one, that uses glDrawElements. Somthing wrong with shadows and it need to be fixed (maybe use fallback code when shadows enabled)

**Comment by a1batross** [comment]
Fixed.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d/commit/81d5f0a30eaa5afe9e4d9fe0d0e1e2504de80ac5

Uhm. This commit fixes them again.
