### ISSUE TITLE
Error: pfnWriteString: exceeds 234 symbols

### ISSUE THREAD

**Issue by THE-Swank** [FWGS/xash3d#201]
Постоянно в логе появляется данная ошибка.
Если верить комментам в заголовочных файлов AMX то аксимальная длина строки должна быть 512 байтов

**Comment by mittorn** [comment]
Похоже что нет. Размер самой мессаги передаётся в байтах. Просто GS не выдаёт ошибку

**Comment by a1batross** [comment]
Помечаю как wontfix и закрываю, так как GoldSrc тоже не разрешает большие мессаги, но попросту не выдаёт ошибку.

**Comment by Severin228** [comment]
Error: pfnWriteString: exceeds 234 symbols
Такая же херня. Как исправить?
