### ISSUE TITLE
Issues with display scaling on Windows

### ISSUE THREAD

**Issue by lukashaertel** [FWGS/xash3d#204]
Since my screen is rather small, I use display scaling on high DPI devices. When this feature is activate, the game will not run in some resolutions. I couldn't run the game in my screen's native resolution 1920x1080, the screen's "center" was shifted and I could not click some of the menu items and the crosshair was off screen. When deactivating the feature, it works fine.

I couldn't find any hints on this in this on the project's website or GitHub page. It would be nice to see it somewhere in FAQs or installation guides, or to have a the program itself run in 100% scaling, rather than system scaling. This feature seems to be called DPI Awareness.

**Comment by a1batross** [comment]
As workaround you can disable scailing for one .exe binary, without disabling it in whole system.

**Comment by a1batross** [comment]
Fixed in https://github.com/FWGS/xash3d/commit/063363bd5175000b71230320111d960dc79a01e7

**Comment by a1batross** [comment]
Note that engine will scale if you change DPI without logout. So, if you changed DPI, logout and then start Xash3D again.
