### ISSUE TITLE
Where are the OpenGL shaders located?

### ISSUE THREAD

**Issue by ShaunNoWay** [FWGS/xash3d#205]
I'm trying to locate fragment and vertex shaders that OpenGL uses to render the game, but I can't find them. Where does Xash3D keep its shaders?

**Comment by a1batross** [comment]
Nowhere. Xash3D renderer don't uses shaders. Just legacy OpenGL 1.x.
Shaders can be used in custom renderers, like Paranoia 2.
07.11.2016 4:11 пользователь "ShaunNoWay" <notifications@github.com>
написал:

**Comment by ShaunNoWay** [comment]
Ah, okay. Thanks.
