### ISSUE TITLE
MinGW build fails due to missing dbghelp.h

### ISSUE THREAD

**Issue by minexew** [FWGS/xash3d#207]
By default, `Makefile.mingw` defines `-DDBGHELP`. This adds a dependency on `dbghelp.h`, which however doesn't ship with MinGW.
There doesn't seem to be a way to disable this without hand-editing the Makefile.

IMO, either the wiki topic should mention where to get the necessary headers or `-DDBGHELP` shouldn't be enabled by default.

**Comment by mittorn** [comment]
Mingw that provided by Debian includes DBGHELP support.
On Windows you may use mingw-w64 project, it also has it included.
I do not know why oficial MinGW does not update it's WINAPI definitions and libs.
Is there any idea to detect when DBGHELP is present from Makefile?

**Comment by minexew** [comment]
Yeah I'm using mainline MinGW, ironically I thought that would be the least painful way.

I'll see what can be done about this.

**Comment by minexew** [comment]
Nevermind, I hadn't realized how broken "official" mingw is with respect to all modern APIs.
And that Mingw-w64 isn't 64-bit-only despite the name.
