### ISSUE TITLE
[Mod Support Request] Chicken Fortress/Chicken Fortress 3

### ISSUE THREAD

**Issue by kuwoh** [FWGS/xash3d#215]
I would love to see this happen
here are the links to the mods i am talking about
http://www.moddb.com/mods/chicken-fortress
http://www.moddb.com/mods/chicken-fortress-3

there are alot of graphical bugs, etc in it
i tried using it with cstrike but it doesn't seem to work as well as i thought it would
if it's too much hard work or if its not worth it just please close this

**Comment by mittorn** [comment]
Mod uses many METAHOOK features and it will hard too port. Note that renderer is closed-source and xash3d does not support vgui2, so some features may not be ported at all.

**Comment by a1batross** [comment]
We don't have plans on VGUI2/GameUI support. Even if renderer would work, HUDs, menus or scoreboard will be unaccessible and will crash the engine.
