### ISSUE TITLE
Can't start QakeRemake

### ISSUE THREAD

**Issue by DI555** [FWGS/xash3d#220]
(win build)
trying as usual with command: "-game ID1"
may be needed some compatibility switch ?

**Comment by a1batross** [comment]
What error it shows?

9 дек. 2016 г. 6:32 AM пользователь "DI555" <notifications@github.com>
написал:

**Comment by DI555** [comment]
xash_mingw.exe -game ID1
================================================================================

        Xash3D FWGS (build 731, Win32-MinGW-i386) started at Apr11 2017 [02:13.2
9]
================================================================================

[02:13:37]  Sys_Warn: invalid mode
[02:13:41]  Sys_Warn: could not revert to safe mode!

================================================================================

        Xash3D FWGS (build 731) fallback to dedicated mode
 at Apr11 2017 [02:13.42]
================================================================================

================================================================================

        Xash3D FWGS (build 731, Win32-MinGW-i386) started at Apr11 2017 [02:13.4
2]
================================================================================

[02:13:43]  Dll loaded for mod Quake
[02:13:43]  server: Playing registered version.
[02:13:43]  execing config.cfg
[02:13:43]  Please add "defaultmap" cvar with default map name to your server.cf
g!
[02:13:43]  Server IP address: 10.0.0.10:27015

**Comment by DI555** [comment]
or the same in console:

Dll loaded for mod Quake
server: Playing registered version.
execing config.cfg
Please add "defaultmap" cvar with default map name to your server.cfg!
Server IP address: 10.0.0.10:27015

**Comment by a1batross** [comment]
[02:13:37] Sys_Warn: invalid mode
[02:13:41] Sys_Warn: could not revert to safe mode!


Engine says you, that your video configuration is wrong. Remove video.cfg
and opengl.cfg from ID1 folder and try again.

2017-04-12 22:31 GMT+03:00 DI555 <notifications@github.com>:

**Comment by DI555** [comment]
my ID1 folder conteins no video.cfg
and opengl.cfg (  ....and ID1 folder didn't have those files (, only:

pak0.pak
pak1.pak
pak2.pak
gameinfo.txt
cached.wad
decals.wad
fonts.wad
gfx.wad

**Comment by DI555** [comment]
I've found the problem of this bug - this errors was when desktop was set to 16bit colors,
after setting desktop to 32bit - all ok.

but when desktop is in 16bit color (like I used to use) - still not starting even with "-16bbp" command key (.

**Comment by mittorn** [comment]
It is SDL2 bug

**Comment by DI555** [comment]
is it listed, planning to fix ?
