### ISSUE TITLE
Unable to download newest release

### ISSUE THREAD

**Issue by Jan200101** [FWGS/xash3d#223]
For about a hour or two me and some other people have been trying to download xash3d but without success everytime we try we get redirected to an error code saying

> <Code>NoSuchKey</Code>
> <Message>The specified key does not exist.</Message>

**Comment by mittorn** [comment]
We cannot fix this right now. We'll contact to Github Support.

**Comment by mittorn** [comment]
http://www.moddb.com/games/xash3d-android/downloads

**Comment by a1batross** [comment]
Use ModDB to download older versions.
