### ISSUE TITLE
Running Xash after build results in error

### ISSUE THREAD

**Issue by Jan200101** [FWGS/xash3d#224]
Ive build Xash3d on arm using cmake 
and make install at the end

now everytime I do xash3d I get this

> pi@raspberrypi:~ $ xash3d
/usr/local/bin/xash3d: 6: [: 32: unexpected operator
/usr/local/bin/xash3d: 12: [: pi: unexpected operator
/usr/local/bin/xash3d: 25: [: Linux: unexpected operator
/usr/local/bin/xash3d: 28: [: Linux: unexpected operator
/usr/local/bin/xash3d: 31: [: Linux: unexpected operator
/usr/local/bin/xash3d: 36: [: Linux: unexpected operator
/usr/local/bin/xash3d: 38: [: Linux: unexpected operator
/usr/local/bin/xash3d: 40: [: Linux: unexpected operator
/usr/local/bin/xash3d: 52: /usr/local/bin/xash3d: /usr/local/bin/: Permission denied

**Comment by a1batross** [comment]
Edit xash3d.sh script first line to #!/bin/bash and type make install again.

**Comment by Jan200101** [comment]
new error

> /usr/local/bin/../lib/xash3d/xash3d: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by Jan200101** [comment]
A new error has appeared.

> pi@raspberrypi:~/Half-Life $ xash3d
Xash3D SDL is installed in system.
[19:19:36]  Sys_Warn: SDL_Init failed:

================================================================================
         (build 622, Linux-arm) stopped with error at Dec13 2016 [19:19.36]
================================================================================

**Comment by a1batross** [comment]
If you want to load Day of Defeat, Counter-Strike or Half-Life: Blue Shift, their client.so libraries are using new private interfaces of engine. They cannot be loaded at this moment.

Other client.so can be loaded. Please, write more about error.

**Comment by mittorn** [comment]
@a1batross, it seems to be an arm device

**Comment by mittorn** [comment]
You need to build client and server manually

**Comment by Jan200101** [comment]
@a1batross @mittorn no I mean half life itself asks for it.
Right I am trying it on a clean Ubuntu with steam and half life installed.
Still the same error

> sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/a1batross/xUbuntu_16.04/ /' > /etc/apt/sources.list.d/xash3d-sdl.list"
sudo apt-get update
sudo apt-get install xash3d-sdl

**Comment by mittorn** [comment]
https://github.com/FWGS/xash3d/wiki/Building-and-running#building-game-mods
https://github.com/FWGS/hlsdk-xash3d
Use microndk or cmake. Do not forget to fix CFLAGS for you platform.
for arm and microndk, set TARGET_ARCH_ABI to arm and correct cflags for your platform

**Comment by a1batross** [comment]
Not a bug?
