### ISSUE TITLE
Ошибка при компиляции

### ISSUE THREAD

**Issue by Nikolay0054** [FWGS/xash3d#225]
http://pastebin.com/ZsF4wUQZ
Стоит ArchLinux x64 c gcc-multilib

**Comment by nekonomicon** [comment]
Как временное решение можно установить флаг **-std=c++98**.

**Comment by mittorn** [comment]
Уже было. Надо бы в master залить исправление

**Comment by Nikolay0054** [comment]
Спасибо, проблема решена
