### ISSUE TITLE
Как собрать hl.so?

### ISSUE THREAD

**Issue by Reedych** [FWGS/xash3d#230]
Хочу пускануть сервак на Ксашике с помощью своей малинки. Всё прекрасно, но я не въехал как собрать hl.so. Под arm у вас был билд, но те файлики в релизе 404-нулись. Спасибо заранее.

**Comment by mittorn** [comment]
https://github.com/FWGS/xash3d/wiki/Building-and-running#building-game-mods

**Comment by Reedych** [comment]
Ааа, понял! Зашёл в hlsdk/dlls, а потом error: make -f ~/microndk/Microndk.mk -j2 и...
`error: expected initializer before '__NDK_FPABI_MATH__'
 long double __builtin_frexpl(long double value, int *) __NDK_FPABI_MATH__; /* fundamentally !__pure2 */
`

**Comment by mittorn** [comment]
конфиг исправил под x86?

**Comment by Reedych** [comment]
Мне нужно на arm, hardfloat.

**Comment by nekonomicon** [comment]
На moddb же лежит сборка под arm, а так лично мне cmake удобней.

**Comment by mittorn** [comment]
@Reedych тогда поставь armeabi и выставь флаги нужные
