### ISSUE TITLE
Иконки для тача

### ISSUE THREAD

**Issue by vlad54rus** [FWGS/xash3d#232]
В редакторе тач кнопок, в списке иконок отображаются только дефолтные иконки из touch_default/
Другие иконки ни в этой, ни в других дирикториях не отображаются, путь к ним приходится прописывать вручную.
Это же касается CS - видны только иконки из хл.

**Comment by mittorn** [comment]
Это относится к меню. проверь как оно работает в меню и если до сих пор не исправлено - создай issue в mainui_cpp
