### ISSUE TITLE
How Can I provide Internet to my server the games take place?

### ISSUE THREAD

**Issue by ms171** [FWGS/xash3d#234]
How Can I provide Internet to my server the games take place?

**Comment by a1batross** [comment]
`NOTE: Set public 1 if you want your server be discoverable through Internet Games section in Xash3D SDL.`

from: https://github.com/FWGS/xash3d/wiki/How-to-set-up-a-Xash3D-Dedicated-Server-on-Debian-or-Ubuntu

**Comment by ms171** [comment]
I couldn't do it.

**Comment by CrusoeDaWolf** [comment]
Just add this line inside server.cfg:
`set public "1"`

**Comment by ms171** [comment]
I did and still doesn't.

**Comment by mittorn** [comment]
Do you have 27015 udp port availiable from the internet?

**Comment by ms171** [comment]
Yes,I did it.

**Comment by a1batross** [comment]
@ms171 maybe you need to have a "white IP". Ask your ISP for about this
service.

Otherwise you can buy a server and host server on it.

2017-02-27 19:37 GMT+03:00 ms171 <notifications@github.com>:

**Comment by ms171** [comment]
I wonder if it could be because I can't do:
Add a repository corresponding to your distro from OBS

**Comment by ms171** [comment]
This is my server.cfg:
https://gist.githubusercontent.com/ms171/852fae1d35389a5dbee6f505e4e53965/raw/a5164c8e0182c3ca3e34701a8394d30702e960ec/server.cfg

**Comment by ms171** [comment]
This is my server.cfg:
https://gist.github.com/ms171/224cb9944a48b4dc04137b0db017a9f8

**Comment by ms171** [comment]
I have solved the problem Thank you.

**Comment by JoelTroch** [comment]
If it's solved, close it
