### ISSUE TITLE
Game crash on loading any map

### ISSUE THREAD

**Issue by RaraFolf** [FWGS/xash3d#235]
After building the latest files for this, and client and server dlls from [this repo](https://github.com/FWGS/halflife/tree/master) (as is linked), I expected to have no issues at all. How horribly wrong I was.

Compiling SDL2 set on Windows 10 with Visual Studio 2013 express results with a full screen window that looks like [this](https://puu.sh/up9OR/159de079cd.jpg) (and crashes if I try to change the screen res or go windowed)  followed by [this](https://puu.sh/upbvQ/23a1f7bbe6.png) nice little error box if I try to load a map.
And [here's](http://pastebin.com/TLaqKDdE) the log it spit out.

Any and all help would be appreciated.

**Comment by mittorn** [comment]
Please compile with dbghelp support (enable DBGHELP macro). Your crash info is unuseful.

**Comment by RaraFolf** [comment]
I've double checked to make sure my files are up to date and compiled all the dlls and the exe with DBGHELP added to the marcos, and instead of crashing on map load it just now does nothing, spitting out this log this time: http://pastebin.com/wYFQyxvW

The dlls are there for sure, and I've noticed that when debugging from visual studio it spits this out:
`'xash.exe' (Win32): Loaded 'C:\workspace\Xash3DStuff\game\testmod\bin\client.dll'. Symbols loaded.
First-chance exception at 0x7792EA5F (ntdll.dll) in xash.exe: 0xC0000139: Entry Point Not Found.
'xash.exe' (Win32): Unloaded 'C:\workspace\Xash3DStuff\game\testmod\bin\client.dll'`

**Comment by mittorn** [comment]
From full log:
```
[2017:03:02|16:03:41] Sys_Warn: Could not load client library:
LoadLibrary failed for bin/client.dll:127
LoadLibraryExt: could not find client.dll!
 ```
Seems that some import dependency missiing

**Comment by RaraFolf** [comment]
It's quite clearly not, yet every single time I try it out it says it is. It's right in the bin folder next to the server dll.

http://puu.sh/usVGT/82914601bb.png

**Comment by RaraFolf** [comment]
I've tested it again with stock WON OpFor dlls (with OpFor included in the gameinfo), and now it loads the client dll but crashes on map load with [this](http://puu.sh/ut06D/75d9425532.png) error box and [this](http://pastebin.com/9qJGQJhy) log.

**Comment by RaraFolf** [comment]
I've now tried loading every single one of Valve's released GoldSrc games on steam, and all of them resulted in [the engine not even recognizing that the client.dll is in the game's proper folders](https://puu.sh/ut3An/42ea7119f9.png), and then to be sure I tried a few old pre-SteamPipe HL1 mods (Scientist Hunt and Counter-Life to be exact) and they resulted in the engine loading the client.dll, but crashing on map load for different reasons.
There is the [Counter-Life](http://pastebin.com/24fbCm4U) and [Scientist Hunt](http://pastebin.com/HDye6BhD) logs.

**Comment by nekonomicon** [comment]
Engine compiled with vgui support?

**Comment by RaraFolf** [comment]
Should have, vgui_support and vgui dlls present.

**Comment by RaraFolf** [comment]
https://puu.sh/utjzS/61a920f27e.png

This should be correct, right?

**Comment by RaraFolf** [comment]
Welp, I feel like a total dipshit now. My entire issue was that I was using a pre-steam vgui dll from around 2001. I have since replaced it with the one from my current steam install of Half-Life and all is working now.

Thank you for your assistance.
