### ISSUE TITLE
Mertcan Server Kurma

### ISSUE THREAD

**Issue by ms171** [FWGS/xash3d#237]
server.cfg:
https://gist.github.com/ms171/224cb9944a48b4dc04137b0db017a9f8

**Comment by trMertcan** [comment]
MS

**Comment by ms171** [comment]
Yes bro

**Comment by ms171** [comment]
Mertcn ordmsn?

**Comment by trMertcan** [comment]
evet burdayım kardesım

**Comment by trMertcan** [comment]
server cfg attıyom olcakmı

**Comment by ms171** [comment]
Kopy yapstr yap.

**Comment by ms171** [comment]
#trMertcan eğer server kapanıyorsa bu linkten metamodun güncelini indir;
http://www.moddb.com/games/xash3d-android/downloads/metamod-p-121p37-custom-build-for-xash3d

**Comment by ms171** [comment]
Bu indirdiğin dosyanın içinde metamod.dll ve metamod.so war bu ikisini bul ve c:/games/xash/cstrike/addons/metamod/dlls için at.

**Comment by a1batross** [comment]
Use English or Russian, please. Or talk somewhere else.

**Comment by trMertcan** [comment]
?

**Comment by trMertcan** [comment]
METAMODU gunceledım

**Comment by trMertcan** [comment]
gıne olmuyo port acmam lazım yoksa olmuyo
