### ISSUE TITLE
Support for Spirit of Half-Life?

### ISSUE THREAD

**Issue by RaraFolf** [FWGS/xash3d#240]
[Spirit of Half-Life](http://www.moddb.com/mods/spirit-of-half-life) allows mappers to do much more without having to get into the nity-grity of coding, and is fully open sourced so anyone can add the new features from it (or base their entire mod off of it, like I am attempting to do), but it is not supported in Xash3D by default.

There is a ton of different versions of it, and all of them are open source, so support for this would be great.
[This](https://github.com/Hammermaps-DEV/Spirit-of-Half-Life-1.8--VC2010/) is the exact version I tried using (after fixing up the weapon defines because some dumbass changed most of them them while only changing some that calls on them) when I [received](https://puu.sh/ut3vS/168725717c.png) this error.

**Comment by nekonomicon** [comment]
You can try build vguiless Spirit of Half-Life v1.8 from this repo: https://github.com/FWGS/SpiritOfHalfLife

**Comment by a1batross** [comment]
Xash3D itself perfectly works with SoHL(and derivatives). 

If you don't see SoHL for your architecture and platform, it's not a problem of Xash3D nor Xash3D FWGS fork. Maybe look into our [repositories](github.com/FWGS). Or read our [porting recommendations](https://github.com/FWGS/xash3d/wiki/Mod-Porting-Guide) to port your mod by yourself.
