### ISSUE TITLE
The first player is getting lost when querying netinfo

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/xash3d#241]
The problem is in this line https://github.com/FWGS/xash3d/blob/master/engine/server/sv_client.c#L766
_count_ is written as char, so it adds terminating \0 when writing the first player (who has index 0).

**Comment by a1batross** [comment]
Seems to be fixed in current development branches: ```server-rework``` and ```build3598```.

**Comment by FreeSlave** [comment]
No, it's the same in both branches
https://github.com/FWGS/xash3d/blob/server-rework/engine/server/sv_client.c#L791
https://github.com/FWGS/xash3d/blob/build3598/engine/server/sv_client.c#L794

**Comment by a1batross** [comment]
My bad, did not noticed this before. 

Fixed in https://github.com/FWGS/xash3d/commit/83868b1cad7df74998ebf2d958de222731241627.

**Comment by FreeSlave** [comment]
Seems to be ok now. Closing.
