### ISSUE TITLE
[server-rework] Crash when client connects to dedicated server

### ISSUE THREAD

**Issue by FreeSlave** [FWGS/xash3d#242]
Dedicated server compiled from server-rework branch crashes when 0.18.1 client tries to connect to it. 

```
[20:17:44]  overflowed
[20:17:44] Warning: reliable overflow for
[20:17:44] Error: NET_CompareBaseAdr: bad address type

Program received signal SIGSEGV, Segmentation fault.
SV_DropClient (drop=0xf71eee90) at server/sv_client.c:499
499             drop->edict->v.frags = 0;
```

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d/commit/a4d652e6e2e54a5f917f28908149e0d774921655

**Comment by FreeSlave** [comment]
Seems to be ok.
But I've had to fully recompile xash binary. Probably some issue with Makefile.
