### ISSUE TITLE
logo.avi not showing up in menus

### ISSUE THREAD

**Issue by ShaunNoWay** [FWGS/xash3d#243]
media\logo.avi doesn't show in menus on the latest release of Xash3D FWGS (0.18.1). My file's not corrupted, since I can have it play on startup by defining it in StartupVids.txt. It's just not showing up in the pause or launch menus anymore.

**Comment by a1batross** [comment]
At first, StartupVids.txt does not control the menu logo. It controls only the "startup" video, which is played during loading. Valve logo, Sierra logo and Gearbox logo, for example. 

At second, logo.avi will not play, if you have Steam-style backgrounds. In any game, not only Half-Life.

**Comment by ShaunNoWay** [comment]
I wasn't trying to get logo to play as a startup video, I was using that as an example to show that Xash3D can find media/logo.avi and that the file itself wasn't corrupted. Though the logo wouldn't show up even when I was using a WON-style background.

I eventually found out it was the `#ifdef USE_VFW` statement in [UI_DrawLogo function](https://github.com/FWGS/xash3d/blob/master/engine/client/cl_menu.c#L133) preventing logo.avi from playing. For whatever reason this always returns false in cl_menu.c, but it works fine in avikit.c (the only other place it's used).
![menu](https://cloud.githubusercontent.com/assets/14033754/24374079/8ac7c798-1301-11e7-9b01-4946ce8a8666.png)

![avikit](https://cloud.githubusercontent.com/assets/14033754/24374078/8ac7a592-1301-11e7-85b3-36f348c8a9e8.png)

Removing this statement makes the logo play in menus again.

**Comment by a1batross** [comment]
Fixed.

**Comment by ShaunNoWay** [comment]
Oops. Just found out this was already fixed in 087c954. I was using an older version that didn't enable USE_VFW macro. Sorry. You can revert 0f0cf60.

**Comment by a1batross** [comment]
Nono, USE_VFW should not be outside avikit.c. Maybe someday avikit.c will be a part of current backend system.
