### ISSUE TITLE
Muzzle flashes (Glock & MP5)

### ISSUE THREAD

**Issue by Matthaiks** [FWGS/xash3d#248]
The muzzle flash is visible during switching guns (no shooting):
![1](https://cloud.githubusercontent.com/assets/3577122/24586423/af7543c4-17a0-11e7-9a31-27df07b90f18.jpg)

The back of the gun is illuminated during shooting:
![2](https://cloud.githubusercontent.com/assets/3577122/24586424/af7a932e-17a0-11e7-9cfd-9e193271366a.jpg)

Xash3D FWGS 0.19, Windows 8.1

**Comment by nekonomicon** [comment]
AFAIK, It fixed in Unkle Mike's Xash3D build 3598.
If you want you can try build 'build3598' branch for testing.

**Comment by Matthaiks** [comment]
Yes, that build is fine.

**Comment by a1batross** [comment]
Now current development branch is build3598.

Unkle Mike will release his Xash3D in April, maybe. So build3598 port will
never see any release. :)

**Comment by Matthaiks** [comment]
Still broken in 0.19.1.

**Comment by a1batross** [comment]
It caused by incompatible client side weapon prediction. I tried to backport reprediction from newer builds, but it doesn't seems to be stable. :(
