### ISSUE TITLE
Мерцание Экрана

### ISSUE THREAD

**Issue by tyabus** [FWGS/xash3d#249]
После обновления с 0.18.1 до 0.19 после свертывания игры и развертывания её обратно, начинает мерцать игра. 1 кадр игры 1 кадр черный. как я определил на глаз, очень хочу чтобы её пофиксили.

------------------------------SYS INFO---------------------------
xash3d v 0.19 Win32 i386
win 7 Максимальная
Monitor: 59 Hz Samsung
--------------------------------END SYS INFO--------------------

**Comment by a1batross** [comment]
Логи? 

Такое поведение записывается какими-нибудь Fraps или аналогами?

**Comment by mittorn** [comment]
@a1batross, там хаглючил мой хак наверно. Я проверю завтра на семёре.
