### ISSUE TITLE
LoadLibrary failed for cl_dlls/client.dll:126

### ISSUE THREAD

**Issue by IgnacioFDM** [FWGS/xash3d#254]
After some struggle I was able to compile on Windows, placed everything (I guess), copied ```steamapps\common\Half-Life```, and I get the error mentioned in the title when launching. After that the game launcher opens correctly but "new game" doesn't work (nothing happens when clicking some difficulty).

**Comment by ShaunNoWay** [comment]
Do you have vgui.dll from the Valve folder beside the Xash3D launcher?

**Comment by a1batross** [comment]
As said @ShaunNoWay, check for vgui.dll and vgui_support.dll.

**Comment by IgnacioFDM** [comment]
Duh. My bad. Got it working now. Thank you. I'll try to compile cs16-client for windows now.
