### ISSUE TITLE
Delta frame

### ISSUE THREAD

**Issue by chinelosabio** [FWGS/xash3d#258]
What is the delta frame and why this message appears every time in which multiplayer game "delta frame is too old: overflow" and after that the game undergoes a fall of fps or a simple rollback, I wanted to know why this happens ...

**Comment by a1batross** [comment]
Ah... Again. Issues ARE NOT question and answers forum. 

Anyway, I will answer you. By simple words: it's indicates network problems. The only way how you can fix it -- change your ISP, country or create a server somewhere more close to you.

Read source code, if you want to know more.
