### ISSUE TITLE
toggleconsole sometimes types grave accent and tilde into console

### ISSUE THREAD

**Issue by ShaunNoWay** [FWGS/xash3d#259]
On Windows 10, using the hardcoded toggleconsole keys, _grave accent_ ``'`'`` and _tilde_ `'~'` will sometimes enter these characters into the input line. I made a cheap fix for myself by adding ``if ( ch == '`' ) return;`` to the [Field_CharEvent ](https://github.com/FWGS/xash3d/blob/24fcfcccd07f1fb97c6ec3adfcfdbaaff0ee10da/engine/client/console.c#L1171) function, but I don't know if this would lead to other issues.

**Comment by a1batross** [comment]
Field_CharEvent is called only when SDL Text mode is enabled. Seems that on Windows 10 text mode is being enabled too early, so '`' or '~' appears in that event, instead of key event.
