### ISSUE TITLE
no evdev_grab command in iOS

### ISSUE THREAD

**Issue by vb87** [FWGS/xash3d#262]
Android version had evdev_grab which worked perfectly to capture mouse. There is only one Cydia package which provides mouse support as far as I am aware of, why can't evdev_grab functionality be added to iOS version?

**Comment by a1batross** [comment]
Evdev input is a Linux kernel feature. It cannot be implemented for other OS than Linux or Android.

 I don't know so much about iOS, there should be similar feature too.

**Comment by mittorn** [comment]
On iOS, native mouse should be availiable with some tweaks, but i do not know if it supported by SDL.
