### ISSUE TITLE
Невидимость игроков

### ISSUE THREAD

**Issue by the-swank** [FWGS/xash3d#264]
Переполнив userinfo буфер можно запросто стать невидимым
![screenshot_2017-05-29-20-24-51](https://cloud.githubusercontent.com/assets/10353528/26557884/5452d990-44ad-11e7-9fd8-8c4cccbf2eef.png)

**Comment by mittorn** [comment]
Тут другая проблема: с какого-то момента перестал работать сброс модели на player.mdl при отсутствии модели на клиенте

**Comment by a1batross** [comment]
@the-swank 
https://github.com/FWGS/xash3d/commit/90fa65ba581e91563ace1610f8ca7a8bf217b6d1

Попробовал исправить. В данной ситуации выходит, что model и name в принципе невозможно затереть. @mittorn, Возможно стоит ещё объявить важными такие ключи как cl_maxpacket, topcolor и bottomcolor, но явно не уровня model и name.

Проверяй. На локалхосте я не смог затереть model.

**Comment by a1batross** [comment]
Закрываю? Вроде как проблема решилась тем коммитом.

**Comment by the-swank** [comment]
Да, исправлено
