### ISSUE TITLE
Won't work with iOS 11.

### ISSUE THREAD

**Issue by JimSleezus** [FWGS/xash3d#268]
xash3d for iOS is a 32 bit app, and won't work on iOS 11.  Could someone please fix this?  Thanks!

**Comment by nekonomicon** [comment]
64-bit version is not stable yet(singleplayer). Needed to rewrite some parts in hlsdk.

**Comment by mittorn** [comment]
I do not have 64bit ios device, so i cannot test it.
If you have device you may try to build and check it. Find amd64 checks in code and add aarch64 to condition.

**Comment by JimSleezus** [comment]
I don't have any method of compilation at the moment, but would be happy to test it on a 64bit device (iOS 10 or 11) if someone can create an iPA file.

**Comment by JimSleezus** [comment]
Are there any updates on the 64-bit version?  Thanks!

**Comment by mittorn** [comment]
No, we do not have 64 bit devices

**Comment by JimSleezus** [comment]
@nekonomicon Aren't you working on a 64-bit update or am I wrong?

**Comment by a1batross** [comment]
Engine now can safely run on 64 bit. It's almost stable.

The problem is now device.

24 сент. 2017 г. 8:04 ПП пользователь "JimSleezus" <notifications@github.com>
написал:

**Comment by JimSleezus** [comment]
@a1batross If you want, I could try to test it?  If all I have to do is side load an iPA, then I can help.  If I had to _build_ it with Xcode, I should still be fine (but don't count on it).

**Comment by a1batross** [comment]
@JimSleezus I actually don't maintain the iOS version. 
AFAIK, @mittorn have uploaded somewhere XCode project for it. You can try adapt it for newer iOS target.

**Comment by nekonomicon** [comment]
@JimSleezus you're doing wrong.
@mittorn added support for 64-bit arches.
I only tested and fixed some bugs, which i can reproduce on my pc with FreeBSD.
I does not have iOS device anyway.

**Comment by cheerless** [comment]
if most of you developers dont have the iOS version, whoever is maintaining the iOS version, and you say that the 64 bit is semi working/stable, maybe release a beta for it, as lots of people are waiting for it

**Comment by MKLGorescript** [comment]
I could test it out, for I have a 64 bit iPhone

**Comment by Kurtisdede** [comment]
Is there any way that I can convert 32-bit apps to 64-bit? I'm still really interested in this.

**Comment by JimSleezus** [comment]
I'm not sure, but I know I would like for this to work for 64-bit devices as well!

**Comment by mittorn** [comment]
https://github.com/mittorn/xash3d-ios/blob/master/README.md

**Comment by Kurtisdede** [comment]
Oh... wow, I can't believe I missed that. I'll be working on this.

**Comment by JimSleezus** [comment]
@Kurtisdede Does this mean you will be releasing anything?

**Comment by Kurtisdede** [comment]
I am now running Mac OS Sierra through VMware, and I'm almost done downloading Xcode. After I port the app to 64-bit (If I even can, I'll try my best though.) I'll ask for permission from mittorn.

**Comment by a1batross** [comment]
I would recommend you to test at least 64 bit build of engine & game for OSX/Windows/Linux only. Xash3D FWGS is cross-platform, so if 64 bit build works on one platform, so the same will work on another platforms as well.

**Comment by Kurtisdede** [comment]
So I've tried to do it, set up SDL2, etc, but there's quite a bit of missing files when I load up the .xcodeproj file. It also keeps saying "Missing file: client_"amods'name"", I thought those were not required.
Also, I don't think you even need a 64-bit iPhone to test this. You can just use the iOS Simulator in the Xcode.

**Comment by mittorn** [comment]
ios simulator does not emulate arm processor
You need to build mods manually.
Change project sample in microndk to generate 64bit projects

**Comment by mittorn** [comment]
ios simulator does not emulate aarch64 CPU
You need to build mods manually. Remove missing files from project and place aarch64 server/client as assets
Change project sample in microndk to make it generate 64bit projects for mods. Note that mods has never built to aarch64 targets. Something may not build at all. Something may cause wrong behaviour, broken level change.

**Comment by mittorn** [comment]
https://transfer.sh/KwHSU/xash3d-armv7.ipa
https://transfer.sh/jc6VG/xash3d-arm64.ipa
Try this
https://github.com/mittorn/xash3d-ios
I have added automatic build scripts and travis script

**Comment by JimSleezus** [comment]
Cydia Impactor won't install the IPAs.  Lol Am I doing something wrong?

**Comment by mittorn** [comment]
I do not know, I do not have device to test it.
Some users with jailbroken ios6 says it ok

**Comment by mittorn** [comment]
@JimSleezus ok, he did not install last build. Last build failed to compile

**Comment by mittorn** [comment]
@JimSleezus Added deploy script
Stripped libraries
libraries for ported mods
https://github.com/FWGS/xash3d-deploy/blob/ios-port-latest/README.md

**Comment by JimSleezus** [comment]
The good news: The iPA installs and functions properly.
The bad news: The game's video freezes as soon as I touch the screen, [as seen here.](https://gfycat.com/WaterloggedEuphoricChevrotain)

**Comment by mittorn** [comment]
Does this build work?
http://rgho.st/8VlNn7PBJ

**Comment by JimSleezus** [comment]
I'm having the same problem.

**Comment by mittorn** [comment]
No, it is npt mp3 player. But some user with ipad mini 2 reported that it works. It is some device-depended bug

**Comment by HotSauce22** [comment]
Multiplayer works, but it still freezes when i look around im on the iPhone 8 Plus btw.

**Comment by mittorn** [comment]
This is bug somewhere in touch.c
I have made separate branch with debug log here:
https://github.com/FWGS/xash3d-deploy/blob/ios-port-touch-debug/README.md
Maybe it help to find where it got wrong value

**Comment by JimSleezus** [comment]
Would you like to see my engine.log file?

**Comment by MKLGorescript** [comment]
Yeah, it seems like the reason the game crashes is because of its "NaN velocity" and "NaN origin". How would we possibly fix this though?

**Comment by mittorn** [comment]
Please send your touch.cfg file if possible.
It seems to be enabled "touch_nonlinear_look" setting. But it is experimental and disabled by default
```
		Msg( "t2 %f %f\n", dx , dy );
		if( touch_nonlinear_look->integer );
		{
			// save angle, modify only velocity
			float dabs = sqrt( dx*dx+dy*dy );
			float dcos = dx/dabs;
			float dsin = dy/dabs;
			
			if( touch_exp_mult->value > 1 )
				dabs = (exp(dabs*touch_exp_mult->value)-1)/touch_exp_mult->value;
			if( touch_pow_mult->value > 1 && touch_pow_factor->value > 1 )
				dabs = pow(dabs*touch_pow_mult->value,touch_pow_factor->value)/touch_pow_mult->value;

			dx = dabs * dcos;
			dy = dabs * dsin;
		}
		Msg( "t3 %f %f\n", dx , dy );
```
It must not enter this block if touch_nonlinear_look disabled

**Comment by mittorn** [comment]
The reason was extra ";" before "if" block. I have fixed this.

Check master branch

**Comment by JimSleezus** [comment]
That seems to have fixed the problem!! Thank you so much!
