### ISSUE TITLE
Invisible players when model does not exist on client

### ISSUE THREAD

**Issue by mittorn** [FWGS/xash3d#274]
After it was fixed in 0.17.1, it was broken again by some commit. I failed to debug it correctly.

**Comment by nekonomicon** [comment]
If run parabot without configs, bots does not have models under xash3d(fwgs 0.17.1 and any other versions), but not GS.
I think player.mdl hardcoded into GS as default model, CS have player.mdl(CT) too.

**Comment by mittorn** [comment]
Check it again, i've ported some hack from GS.

**Comment by nekonomicon** [comment]
https://github.com/FWGS/xash3d/pull/275/commits/337002f01f9bc2a4568cdc7dff01236ef1c55007

**Comment by mittorn** [comment]
Still can reproduce?

**Comment by mittorn** [comment]
Fixed
