### ISSUE TITLE
Unable to start singleplayer game

### ISSUE THREAD

**Issue by RalfVB** [FWGS/xash3d#278]
Hello,

I just installed Xash3D on x64 Linux (Xash3D FWGS build 731). Installed Half-Life from the original retail CD using Wine, entered it's cd key, updated it to v 1.1.1.0 then copied the valve folder into my xash3D folder, copied client.so and server.so into the xash3D folder root, and launched it.

Everything appears to work just fine, except that I cannot launch a single player game. 'New game' is greyed out. I can play matches online without issues.

Same thing goes for Opposing Force. I can start the mod, but 'New Game' is not available.

Edit: Okay, I figured out server.so needs to be renamed to hl.so and put in /valve/dlls.

'New game is now available', but it won't progress if I click a difficulty setting.
I can open singelplayer maps via the console though.

So where do I get the server libraries to run opposing force and blue shift?

**Comment by nekonomicon** [comment]
>'New game is now available', but it won't progress if I click a difficulty setting.
I can open singelplayer maps via the console though.

Can you attach liblist.gam and gameinfo.txt?

>So where do I get the server libraries to run opposing force and blue shift?

1. Steam.
2. [dll loader](https://github.com/FWGS/xash3d/wiki/Building-and-running#using-dll-loader)
3. We have recreated [Blue Shift source code](https://github.com/nekonomicon/hlsdk-xash3d/tree/bshift) by Unkle Mike, you can try build it manually.

**Comment by RalfVB** [comment]
Hi,

Thanks for your reply. I looked at liblist.gam, and adjusted the gamedll_linux key to the correct file name.
Launching games now works flawlessly. Great :)

Going to try and get Opposing Force and Blue Shift working now.

**Comment by ryan-sg** [comment]
A bit late, but I noticed on my OpenBSD/amd64 system I had to name the file 'client64.so' to be automatically picked up by xash3d.  The server dll was fine as just being hl.so.  I didn't know about liblist.gam though, cool :-)
