### ISSUE TITLE
Пропажа сервера из списка серверов после смены карты

### ISSUE THREAD

**Issue by the-swank** [FWGS/xash3d#280]
Сервер пропал из списка серверов после перезагрузки на другую карту, после его перезагрузки было в логе сообщение о добавлении сервера в список серверов, но в списке серверов он так и не появился, спустя 10 минут ожидания нечего не изменилось, появился только после полной перезагрузки процесса сервера.

**Comment by the-swank** [comment]
Происходило подобное и раньше

**Comment by mittorn** [comment]
А сервер после этого по сети доступен?

**Comment by the-swank** [comment]
Да, работает как обычно, просто нет в списке серверов

**Comment by the-swank** [comment]
Глянул в GDB на баг, там NET_StringToAddrNB() в Master_Add() возвращает 2 постоянно и в итоге Master_Add() вызывается каждый кадр, но запрос на мастер сервер не отправляется, постоянно срабатывает условие `res == 2`

**Comment by mittorn** [comment]
2 означает ожидание. перечитаю код как будет время

**Comment by the-swank** [comment]
Проблема заключается в потоках, без USE_PTHREAD работает нормально

**Comment by mittorn** [comment]
Может, оно у тебя как-то по другому работает? Какие-то особееные потоковые проблемы? У себя не наблюдал проблем с ним. Можно конечно убрать его для дедика, на сервере это не так критично - нет подвисания интерфейса. Но ведь сервер тоже в идеале не должен подвисать.
Ещё можно кэшировать результат ответа мастера, но тогда при смене адреса сервер придётся рестартить

**Comment by mittorn** [comment]
Попррбуй добавить volatile в состояния pthread, может оно оптимизировалось как-то?

**Comment by mittorn** [comment]
Fixed
