### ISSUE TITLE
Крашит на Android 2.2.1

### ISSUE THREAD

**Issue by toqrul2000** [FWGS/xash3d#285]
Приложение Xash3d на Samsung Galaxy S (gt-i9003, 2.2.1) крашится с первого запуска. Скачана с Play Market-a. Не успевает открыться как сразу "Процесс неожиданно остановлен". При этом cs16client совершенно спокойно открывается. Будьте добры, пофиксите.

**Comment by toqrul2000** [comment]
Краш наблюдается как в автономном запуске, так и через клиент кс

**Comment by a1batross** [comment]
Качай версию с гитхаба. 

Версия для Play Market не работает с 2.2. Не закрывай, потом исправлю в gp-ветке.

**Comment by mittorn** [comment]
Звук вряд ли будет работать. Официально в 2.2 не было OpenSLES. Но отпишись всё же, заработает ли, самсунг запросто мог добавить

**Comment by toqrul2000** [comment]
Скачал последнюю версию с гитхапа. Программа запустилась. Но в кс поиграть не удалось. После нажатия "Запустить cs16client" кроме черного экрана ничего не происходит. А если запустить сразу из xash то выходит error:
Sys_crash:signal11, err 0 with code 1 at ox4f ox809a73c0 stack backtrace: и дальше 31 пункт.

**Comment by a1batross** [comment]
O_o

Точно последняя версия?

15 авг. 2017 г. 3:11 ПП пользователь "toqrul2000" <notifications@github.com>
написал:

**Comment by toqrul2000** [comment]
Вот эта: https://github.com/FWGS/xash3d/releases/tag/v0.19

**Comment by mittorn** [comment]
half-life запускается? engine.log можешь прикрепить?

**Comment by toqrul2000** [comment]
Халва тоже не запустилась, вот лог:
https://drive.google.com/file/d/0B7w7-YODjw-Kb1NZYktmczBFaXM/view?usp=drivesdk

**Comment by toqrul2000** [comment]
Upd:.переместил папку xash в /mnt/sdcard (раньше была в ... /Android/obb), количество ошибок уменьшилось. Вот новый лог:
https://drive.google.com/file/d/0B7w7-YODjw-KbjJzNUhXOFk0OGc/view?usp=drivesdk

**Comment by toqrul2000** [comment]
Стоит отметить что на планшете (4.4.2) при запуске халвы тож появляются проблемы, но с кс все нормально. Проблема скорее с кешем. Но почему тогда кс на планшете запускается, а на телефоне - нет.(?)

**Comment by a1batross** [comment]
Боюсь знать, что у вас игра делает в /Android/obb.

Может стоит просто переложить во внутренней памяти в папку xash?

>[2017:08:16|13:37:32] ^1Error:^7 FS_AddPack_Fullpath: unable to load pak
"/data/data/in.celest.xash3d.hl/files/extras.pak"
Странно, походу распаковка не сработала. Удалите движок и установите его
обратно.

Запишите ещё раз лог с "-dev 5" в аргументах командной строки, последний
лог почему-то неполный.

**Comment by mittorn** [comment]
на 2.2 пак не распакуется сам, он слишком большой.
https://github.com/FWGS/nanogl/blob/master/nanoWrap.cpp#L1668
Краш тут. нужен андройдовый лог чтобы понять, почему не загрузился GLESv1
Может быть, устройство не поддерживает его совсем?
TODO: добавить коллбэки для вывода лога в nanogl и убрать костыли касательно загрузки egl через него. egl должен грузить движок, а ошибки nanogl лолжны попадать в основной лог

**Comment by mittorn** [comment]
есть ли файл /system/lib/libGLESv1_CM.so?

**Comment by toqrul2000** [comment]
Да

**Comment by toqrul2000** [comment]
Доброго дня, стоит ли мне ждать update? Или можно забыть про игру на старом девайсе?

**Comment by mittorn** [comment]
Пока нет, информации мало.
Можешь сделать logcat?

**Comment by toqrul2000** [comment]
Подскажите, как сделать?

**Comment by mittorn** [comment]
logcat>/sdcard/logcat.txt в терминале сразу после краша
Потом выложить logcat.txt

**Comment by mittorn** [comment]
Проблема уже исправлена?:

**Comment by toqrul2000** [comment]
К сожалению накрылся Samsung. Если смогу вернуть его к жизни, обязательно проверю.
