### ISSUE TITLE
Why does xash not run?

### ISSUE THREAD

**Issue by sourceskyboxer** [FWGS/xash3d#286]
Hello arrogant Russians, 

why do I not understand? I already copied Half-Life from Steam to FWGS Xash than it won't run?

How do I fix?

**Comment by nekonomicon** [comment]
>why do I not understand? I already copied Half-Life from Steam to FWGS Xash than it won't run?

Can you provide more information?

**Comment by sourceskyboxer** [comment]
![fucking_error_of_xash](https://user-images.githubusercontent.com/3496136/29686415-29fc8c62-8919-11e7-8261-e48cba9d0d9f.JPG)
![fwgs_xash_with_valve](https://user-images.githubusercontent.com/3496136/29686480-5e9450b8-8919-11e7-9134-8796af8bdb90.JPG)

I can not resolve. :( How do I fix?

**Comment by nekonomicon** [comment]
>But why does it always very bright please make normal gammar of game-viewport
Specially for android users.
Type **gamma 1** in the console.

**Comment by mittorn** [comment]
gl_ignorehwgamma 1 in opengl.cfg

**Comment by a1batross** [comment]
It runs? If so, I close this issue.

**Comment by sourceskyboxer** [comment]
Thanks for help me now I close now

Where is "Comment and close"
