### ISSUE TITLE
Алгоритм генерации authid не обеспечивает статичность authid

### ISSUE THREAD

**Issue by the-swank** [FWGS/xash3d#288]
Начали жаловатся на дубли в статистике(она по authid), глянул в БД, а там действительно дублей достаточно, все как один твердят, что играли с одного устройства и даже с одной версии

**Comment by mittorn** [comment]
Ох уж эти китайцы. У них ещё наверно android id одинаковый. Я нашёл ещё несколько источников идов, добавлю. Но не факт что оно сработает.

**Comment by the-swank** [comment]
Судя по всему исправлено, в настоящий момент у каждого игрока статичный authid

**Comment by a1batross** [comment]
На самом деле. Есть такие вредные прошивки, вроде Kali Linux(сам удивился, что оно вообще есть для Android. На самом деле сборочка цианогенмода с кали поверх).

Так вот они любят менять мак адрес спустя какой-то промежуток времени. Статичности ксашида это ни разу не помогает. :)

**Comment by mittorn** [comment]
Так ничего не меняли в ксашиде с 0.19 пока. Но я не хочу сделать хуже, по этому не факт что буду менять это. Если понизить порог для смены, то статичность может пострадать
