### ISSUE TITLE
Doesnt log on linux

### ISSUE THREAD

**Issue by ridvan1995** [FWGS/xash3d#291]
Hi. Sometimes my servers are crashing. And i cant the problem because xashds isnt logging. How do i activate logging?

**Comment by a1batross** [comment]
-dev N sets log level. 1 is minimal, 5 is everything.
-log forces engine to write log on disk, to engine.log file.

**Comment by ridvan1995** [comment]
Thanks! I didnt know that i must use -dev for logging

**Comment by a1batross** [comment]
Since 0.19 you can pass a -help to command line to get engine help.
