### ISSUE TITLE
Build 3887 porting

### ISSUE THREAD

**Issue by a1batross** [FWGS/xash3d#302]
Fork is every day is more far from his parent. So updating to new code base is more harder. This issue is intended to discuss build 3887 porting.

**Comment by fuzun** [comment]
I think main priority must be porting from its base therefore keeping the code base up to date at an initial level.

**Comment by D0ve** [comment]
Очень ждём. Но есть ньюанс, будет ли возможно опционально прикрутить поддержку OpenGL и поддержку загрузки внешних текстур?    ...ведь насколько понимаю, ДядяМиша их выпилил(.

**Comment by a1batross** [comment]
3887 porting is delayed until stable Xash3D 1.0 releases.

**Comment by a1batross** [comment]
Re-fork: github.com/FWGS/xash3d-fwgs.
