### ISSUE TITLE
CL_IsThirdPerson should not be called on disconnecting client

### ISSUE THREAD

**Issue by mittorn** [FWGS/xash3d#305]

**Comment by a1batross** [comment]
It's by design should not be cached, as it engine does now. We should or move it somewhere else, or replace cl.thirdperson by CL_IsThirdPerson everywhere.

**Comment by a1batross** [comment]
Fixed by https://github.com/FWGS/xash3d/commit/267935b7355e2e724a88e76f8eeced4510175bda
