### ISSUE TITLE
Отмена рикошета

### ISSUE THREAD

**Issue by Tarik02** [FWGS/xash3d#317]
К примеру у меня есть Entity который летит(MOVETYPE_FLY, SOLID_BBOX). При ударе об другой я убиваю второго и хочу чтобы первый продолжил лететь так, как и летел. Как это сделать?

**Comment by nekonomicon** [comment]
Не баг. Спроси на http://cs-mapping.com.ua.

**Comment by mittorn** [comment]
Штатной физикой не предусмотрено. Можешь попообовать сделать SOLID_TRIGGER и сделать это  в Touch().

**Comment by Tarik02** [comment]
@mittorn, с SOLID_TRIGGER почему-то не вызывается Touch
