### ISSUE TITLE
Не работает con_color

### ISSUE THREAD

**Issue by LostGamerHL** [FWGS/xash3d#319]
Когда вводишь con_color "r g b" в консоль цвет меняется, но после выхода с консоли он сбрасывается на стандартный.

**Comment by a1batross** [comment]
Поправлю. Это зависит от ресайза. Всё равно баг, но дело не в выходе из консоли.

**Comment by a1batross** [comment]
Fixed in Alibek a1batross Omarov:
Commit #3f61ff5 at FWGS/mainui_cpp
https://github.com/FWGS/mainui_cpp/commit/3f61ff5606c203ab646d7c2147431f2d326cbf7d. 

Will arrive when mainui_cpp will be updated in engine.
