### ISSUE TITLE
Autotools скрипты сборки

### ISSUE THREAD

**Issue by the-swank** [FWGS/xash3d#322]
Сделал себе для удобной компиляции скрипты autotools https://github.com/the-swank/xash3d/commit/e26bdf41f95aef8c6de1fbd0c8f9d5fa2cba955a , могу отправить PR доделав всякие мелочи по типо libloader и сборки сервера не требуя SDL, но сомневаюсь что 4(это без учета 3 дополнительных Makefile в engine помимо Makefile.linux) система сборки кому-то нужна, я могу поддерживать только нормальную сборку серверной части под linux и средка проверять сборку клиентской части под linux без проверки libloader и т.п опциональных фич

**Comment by a1batross** [comment]
Не нужно плодить сущности. 

Есть CMake и Android.mk, это единственно поддерживаемый путь. 
Makefile-ы же deprecated и если mittorn не будет их вовремя обновлять, то они будут удалены.

**Comment by mittorn** [comment]
Лучше уж тогда сделать скрипт который скачает зависимости или соберёт deb/rpm. autotools хорош тем что позволяет тонко настраивать сборку, сам выдавая при этом справку и проверяя зависимости. Это можно заменить сопроводив текстовым файлом с описанием опций и установки зависимостей для популярных ОС (у нас уже есть вроде такой).
