### ISSUE TITLE
Is there a release or a way / instructions to build for raspberry pi?

### ISSUE THREAD

**Issue by Lion4K** [FWGS/xash3d#329]
I really wanna play half life and or counter strike on the pi.

Thanks and sorry if this is a bad place to ask this.

**Comment by a1batross** [comment]
As far as I know, there is an experimental GL driver for RPi. You can just compile default Linux version of engine and HLSDK(see hlsdk-xash3d repo). It's a easiest way, which will also give you some free framerate. :)
I found a tutorial here: https://eltechs.com/how-to-enable-opengl-on-raspberry-pi/

If you want to use GLES, just pass  -DXASH_GLES=1 to CMake while compiling engine and use glshim or nanogl, as GL to GLES translator.

**Comment by Lion4K** [comment]
I see, I'll give it a shot.
Also I'm using retropie, it's a dedicated gaming distro, I believe that it's already enabled on the drivers.

**Comment by a1batross** [comment]
Any success here? :)

**Comment by Lion4K** [comment]
not really no, my board is dead, idk what i did.
this is gonna wait till i have money to buy a new one, i'm unemployed too, so, it might take some while.
:'-(

**Comment by a1batross** [comment]
Woah. I hope it's not because you have enabled extended driver?

**Comment by Lion4K** [comment]
No, I believe it was a power surge.
Bc I tested the PSU with other device and the PSU was dead too.

**Comment by Lion4K** [comment]
And I belive the experimental GL is already turned on in those gaming distros such as retropie.

**Comment by Lion4K** [comment]
I didn't even managed to test any of this as I purchased the board, downloaded that image, used for a short while, had to go on a trip, but I forgot to take it out of the wall socket. when I got home it was already dead.

**Comment by a1batross** [comment]
It's sad. :(

**Comment by Lion4K** [comment]
yeah.
Also, I just realized, I don't make any idea on how to compile anything to RPI.

The most I had compiled was once a Minecraft plugin from a github, and thats it.

Should I use Git for Windows to do this?
Gonna try the RPI emulator.

**Comment by a1batross** [comment]
Compiling is easy. 

Take a look at [our wiki](https://github.com/FWGS/xash3d/wiki/Building-and-running).

But if you want crosscompile from PC to RPi, you need to set up compilers for CMake manually. Look at CMake documentation.

**Comment by Lion4K** [comment]
so if I boot up to raspbian I should be able to compile just following the wiki?

**Comment by mittorn** [comment]
If raspbian supports GL and has development packages (such as libsdl2-dev), you may just build following the wiki. (I hope, cmake scripts will not add -m32 to cflags on arm? Otherwise build will fail)

a1batross, Try add nanogl/wes/regal support to cmake if still not. Something like `-DWITH_NANOGL=/path`/to/nanogl

**Comment by Lion4K** [comment]
My version does not even have the GL experimental option. lol.
![image](https://user-images.githubusercontent.com/10391955/34322140-84ba45ee-e806-11e7-82cc-ad7018af5f70.png)

**Comment by a1batross** [comment]
@mittorn yeah, I forgot to add this case.

**Comment by mittorn** [comment]
And SDL2 need GLES support too when using GLES.
If SDL2 built with enabled desktop gl, it will not be possible to use GLES with it.

**Comment by Lion4K** [comment]
OK, so just to clarify.

Im at this part:

On 32 bit systems:

cmake -DHL_SDK_DIR=../hlsdk -DXASH_SDL=yes -DXASH_VGUI=yes ../ && make
On 64 bit systems:

cmake -DHL_SDK_DIR=../hlsdk -DXASH_SDL=yes -DXASH_VGUI=yes -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m


on the RPI emulator. should I choose what?

**Comment by Lion4K** [comment]
using CMAKE btw, i installed it via apt-get

**Comment by Lion4K** [comment]
I got an Error using thr 32bit line.

http://pastebin.com/H6wMDc4Q

**Comment by a1batross** [comment]
Install libsdl2-dev.

**Comment by Lion4K** [comment]
inside the xash3d folder?

**Comment by Lion4K** [comment]
will libsdl1.2debian cut it?
theres also a ton of others there but no libsdl2-dev

**Comment by a1batross** [comment]
Yes, run git inside xash3d folder. 

sdl1.2 is a legacy version. You need sdl2. Use apt search to find sdl2 development package.

**Comment by Lion4K** [comment]
there is no sdl2 there. only libwsdl2-java 
a stripped down axis2 source bundle situable for running WSDL2C
Whatever that ^ means lol

**Comment by a1batross** [comment]
I dunno why it isn't here. Try to use google on how to install SDL2 on your RPi distro.

**Comment by Lion4K** [comment]
Gonna try after the holidays.
Have a nice xmas folks!!

**Comment by a1batross** [comment]
Installing on RPi should be like for other any Linux distro. RPi isn't special.
