### ISSUE TITLE
[Android] SD Card permissions.

### ISSUE THREAD

**Issue by Lion4K** [FWGS/xash3d#332]
Hi, as I believe you devs already know, theres a issue with the SD Storage access on Kit Kat or later android versions.
However I'm here to present a possible solution.

I've seen some apps bypassing this, by using android's internal file picker, and some others have implemented something that makes the app asks the system for SD Card privileges, which in its turn asks the user about it.

This may provide some help.
https://source.android.com/devices/storage/

Again, I'm not a developer, I have little to no knowledge on android developing, the most I know is to use ADB / Fastboot to custom rom procedures, and logcats.
I'm just trying to be helpful.

Happy new year!!

**Comment by mittorn** [comment]
It does not work for native code and it is very slow. Yes, we may wrap filesystem to java, but it is hard task, it will not be compatible with mods, it will be slow and increase memory usage. 0.5s hanging on save,download,changelevel,graph write, reducing connection time 2-3 times because of demoheader. And it may crash/hang because of buggy implementations.
Use "rodir" feature in test versions, it is fast enough and compatible with half-life game code (but not with aghl, xdm, etc...).

**Comment by mittorn** [comment]
P.S you yell about file picker method which does not work, but android 6.0 method with /mnt/runtime may work. I do not have android 6.0+ devices to check if it useful.

**Comment by Lion4K** [comment]
I can test that for you if you want. I can also point to some apps that uses that method that you may be able to take a look at and idk, make sense out of something there, idk jack about that.

**Comment by a1batross** [comment]
It does not depends, request you SD card privileges or not, it will not available from native code. 

Rodir is seems to be best solution here.

**Comment by Lion4K** [comment]
Solid Explorer is one of the apps that Uses that. I made a video showing how that happens. 
heres the link to it: https://www.youtube.com/watch?v=sss2DPo6_hA

**Comment by Lion4K** [comment]
BTW whats Rodir?

**Comment by Lion4K** [comment]
Also, how ironic is that, Solid Explorer, a file explorer that relies on android's own file explorer to work. lol;

**Comment by mittorn** [comment]
Does Solid Explorer performing file operations in native code?
If it uses documents api, this method unuseful for xash3d.

**Comment by Lion4K** [comment]
Here's the correct Link:
https://www.youtube.com/watch?v=EP20YbnZBc4

**Comment by Lion4K** [comment]
No I belive it's not native, at least if I understood what native is.

**Comment by Lion4K** [comment]
I mean, I have no idea.

**Comment by mittorn** [comment]
Use /sdcard/xash as game folder, but leave it empty and place game data to /storage/sdcard1/xash and add -rodir /storage/sdcard1/xash to command-line arguments.

**Comment by mittorn** [comment]
Documents API is only availiable in java code. It is different from classic filesystem. It is similar to downloafing files from network Instead of reading.

**Comment by mittorn** [comment]
File managers "uploads" files to sdcard, and does nlt write it directly.

**Comment by Lion4K** [comment]
So "Path to game resources" I set what?

**Comment by mittorn** [comment]
To /sdcard/xash which should be empty. Xash3D will write all changed files there. It will be used as overlay to read-only /storage/sdcard1/xash

**Comment by Lion4K** [comment]
could not found directory valve.

**Comment by Lion4K** [comment]
like, my sdcard path is /storage/F2ED-255F/

**Comment by Lion4K** [comment]
so my Advanced Tab should be:

Command line ar(...)
-dev 3 -log -rodir /storage/F2ED-255F/xash

Path to game resources:
/storage/emulated/0/xash 

Pixel format (...)
32Bit

Keyboard does not resizes 

Check updates Tick

Update to unstable Untick

enable immersive mode (...) Tick

**Comment by a1batross** [comment]
Forgot to say, it works only on test versions.

**Comment by Lion4K** [comment]
Oh. Where do I get this version?

**Comment by mittorn** [comment]
https://github.com/FWGS/xash3d-deploy

**Comment by a1batross** [comment]
Read READMR.md file. Use "travis-latest" branch.

**Comment by Lion4K** [comment]
This?
https://github.com/FWGS/xash3d-deploy/blob/travis-0.19.x/xash3d-generic.apk?raw=true

**Comment by a1batross** [comment]
Yes.

2 янв. 2018 г. 9:50 ПП пользователь "Lion de Oliveira Lorena" <
notifications@github.com> написал:

**Comment by Lion4K** [comment]
thanks, gonna copy the files one more time, as google play music keeps playing the media files on the game folder.

**Comment by Lion4K** [comment]
works nicely. thanks.

**Comment by Lion4K** [comment]
except not for any other mod rather than original HL.

**Comment by mittorn** [comment]
Try add dot (.) to folder name. It will hide it ftlm file managers and media scanner.

**Comment by Lion4K** [comment]
hmm, gonna try that. thanks.

**Comment by Lion4K** [comment]
Oh, nvm, I went to do that, but I just remembered I tried something else and It worked like a charm.

I made a new text file on windows, and with the help of cmd I renamed it to ".nomedia" and then copied it to xash folder and then each subfolder like valve, cstrike, etc.

I went to verify if it worked and it did.
But perhaps your method is easyier, i'm gonna use it next time.

**Comment by mittorn** [comment]
android may remove media files from folders with .nomedia, so i not recommend using this method

**Comment by a1batross** [comment]
@mittorn you need to have a very-very special luck for this. :)

**Comment by a1batross** [comment]
@Lion4K for mods you should add the same command argument in the mod's launcher.

**Comment by mittorn** [comment]
@a1batross
No, just add .nomedia after mediascanner adds files to database

**Comment by a1batross** [comment]
Nope. It's a bug. I don't even think it exist on modern Android. (Yes, I
think 4.x branch isn't a modern).

3 янв. 2018 г. 3:27 ПП пользователь "mittorn" <notifications@github.com>
написал:

**Comment by mittorn** [comment]
I do not know if ti is bug or feature, but i do not recommend to use it as Samsung devices may have it enabled.

**Comment by Lion4K** [comment]
im using androis 7.1.1, waiting motorola release oreo.

**Comment by Lion4K** [comment]
but yeah the .nomedia file worked like a charm. not only stopped music but also pictures.

**Comment by Lion4K** [comment]
for the mods. lets say i wanna use Crack-Life.
What should I use?
folder name is cracklife.

r/n i'm using:

advanced:

cmd args
-dev 3 -log -rodir /storage/F2ED-255F/xash -game cracklife

Path:
/storage/emulated/0/xash


should I add cracklife to both lines?

**Comment by nekonomicon** [comment]
You must place cracklife folder to xash folder.

**Comment by Lion4K** [comment]
yeah, it is.

all my mods are there

cracklife
clcampaign
cstrike
czero
czeror
valve
ricochet
dmc
etc etc etc

**Comment by Lion4K** [comment]
Would be this one the native thing you were talking about?
It sure does look different from the one I showed on the video. 

Teste https://imgur.com/gallery/FZGTF

**Comment by Lion4K** [comment]
It asks directly to the folder and not the whole card.

**Comment by mittorn** [comment]
rewrite xash3d to java and it will work

**Comment by Lion4K** [comment]
When you mean rewrite, isn't it already in Java?
I mean I thought everything in Android was Java, actually Dalvik something idk. I saw something on college but didn't pay attention.

**Comment by nekonomicon** [comment]
Xash3d was written on pure C(menu and game libraries on C++).
Only launchers(black windows) was written on Java.
You can write apps for android on any program language in combination with Java.
Dalvik - just Oracle's JVM implementation for android.

**Comment by Lion4K** [comment]
I see, I guess I should had payed more attention to college lol

**Comment by Lion4K** [comment]
Well, about the other mods, I still can't get them to work, how should I fill both lines, like, for example for CrackLife.

cmd args
-dev 3 -log -rodir /storage/F2ED-255F/xash 

Path:
/storage/emulated/0/xash

Should I use "-game cracklife" on both of them?

**Comment by a1batross** [comment]
Everything is just like Half-Life, except you need to pass -game cracklife
to command line arguments. And also you may have "cracklife" on your "
/storage/F2ED-255F/xash"

**Comment by Lion4K** [comment]
but the -game comes after or before -rodir? or it doesn't matter?
because it didn't worked.

I've used exactly like this:

cmd args
-dev 3 -log -rodir /storage/F2ED-255F/xash -game cracklife

Path:
/storage/emulated/0/xash

**Comment by a1batross** [comment]
It doesn't matter at all.

**Comment by Lion4K** [comment]
hm, yeah, it does not work at all.

**Comment by Lion4K** [comment]
BS Launcher doesn't work either.

**Comment by Lion4K** [comment]
Both CrackLife and BlueShift reaches main menu, but does not load any maps. you keep clicking the example "hazard course" and doesn't do anything.

In BS Launcher I used the line -dev 3 -log -rodir /storage/F2ED-255F/xash and it did load the main menu blue background. but still not loading any maps.

**Comment by a1batross** [comment]
No log, no honey.

7 янв. 2018 г. 12:40 ДП пользователь "Lion de Oliveira Lorena" <
notifications@github.com> написал:

**Comment by Lion4K** [comment]
I didn't knew log as necessary, where is the log?

**Comment by Lion4K** [comment]
Is this the log?

https://pastebin.com/QGabXNPW

**Comment by a1batross** [comment]
Re-run engine with -dev 5 -log, it will print more info to the engine.log.

7 янв. 2018 г. 10:50 ДП пользователь "Lion de Oliveira Lorena" <
notifications@github.com> написал:

**Comment by Lion4K** [comment]
dev 5 log
https://pastebin.com/5mzumGWj

**Comment by a1batross** [comment]
Thanks, it seems bug of RoDir. It doesn't adds basedir from rodir before
everything.

**Comment by Lion4K** [comment]
glad i could help somehow.

**Comment by a1batross** [comment]
Was fixed in dd3580d56c3fd06d0a62330d294097b2caaa31ea.
