### ISSUE TITLE
Rewrite the code under a 3rd party license to fully adhere to the terms of the GPLv3 license 

### ISSUE THREAD

**Issue by Bitl** [FWGS/xash3d#333]
Hi,

I have noticed that a portion of this engine's codebase includes 3rd party licenses from ID Software to Valve. This causes issues with commercial games using this engine, especially if you want to use a platform like Steam for distribution. Maybe rewrite the affected code or alter parts of it (like what happened with Carmack's reverse) to make this project fully GPLv3 compliant.

**Comment by nekonomicon** [comment]
Some hlsdk headers looks as fully identical or close to quake headers under GPLv2+. We can just replace hlsdk headers on quake headers and increment license version, but some parts need to rewrite.

**Comment by a1batross** [comment]
There is only headers which don't follow the GPLv3 license. Any other files are GPLv3 compliant.
