### ISSUE TITLE
AMX 1.8.3 g_pGameRules address could not be found

### ISSUE THREAD

**Issue by NeonXash** [FWGS/xash3d#334]
Чем исправить Ошибку ?

[FAKEMETA] get/set_gamerules_* natives have been disabled because g_pGameRules address could not be found. 
client_disconnected and client_remove forwards have been disabled - check your gamedata files.
Binding/Hooking cvars have been disabled - check your gamedata files.
filesystem_stdio exists and loaded!

Через неделю лог весит уже тонну ..

**Comment by mittorn** [comment]
Вроде это не касается движка

**Comment by a1batross** [comment]
Движка это касается тем, что он не голдсорс. :)

**Comment by NeonXash** [comment]
Hа рехлдс тоже были проблемы с этим ..
лечилось этим 
https://forums.alliedmods.net/showpost.php?p=2392027&postcount=29

но на ксаше не катит ) значит нужно чтото другое изменить, токо что ? )

**Comment by a1batross** [comment]
Движок тут ни при чём.
