### ISSUE TITLE
Не отображается часть текста в чате

### ISSUE THREAD

**Issue by Perevozzz** [FWGS/xash3d#335]
![screenshot_20180106-143555 1](https://user-images.githubusercontent.com/35170619/34640668-ecc00aaa-f307-11e7-8e63-8f5ac8fc6c03.png)

![screenshot_20180106-143218 2](https://user-images.githubusercontent.com/35170619/34640661-da0c52f6-f307-11e7-90cd-5e40d80ae1df.png)
Привет всем.
Заметил такой баг, я установил плагин, который должен выводить в чат кто подсоединяется к серверу и с какой страны, но проблема в том, что вместо текста показываются пустые полосы в чат. То же самое и с плагином випа, где в чат должна выводится надпись "на сервер подсоединяется вип"ник"". Оба плагина не требуют инклуида colorchat.

[296_5476_connectipc.zip](https://github.com/FWGS/xash3d/files/1608871/296_5476_connectipc.zip)

**Comment by a1batross** [comment]
Вообще это баг cs16client, но я не знаю как тут переносить ишью из одного
места в другое, а нормального багтрекера у нас пока нет.

6 января 2018 г., 17:31 пользователь Perevozzz <notifications@github.com>
написал:

**Comment by a1batross** [comment]
Исправил в клиенте. Рекомендую смотреть КУДА отправляете issue. =/
