### ISSUE TITLE
Cant compile on Gentoo

### ISSUE THREAD

**Issue by hpagseddy** [FWGS/xash3d#337]
Hi, im trying to compile Xash3D on x86_64 Gentoo, but i got VGUI error
---log---
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'fontconfig'
--   Found fontconfig, version 2.12.4
<FindVGUI.cmake>
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find VGUI (missing: VGUI_LIBRARY VGUI_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindVGUI.cmake:87 (find_package_handle_standard_args)
  vgui_support/CMakeLists.txt:40 (find_package)
---log---

**Comment by a1batross** [comment]
You can use (official HLSDK)[https://github.com/ValveSoftware/halflife] or just VGUI binary and header from (vgui-dev repository)[https://github.com/FWGS/vgui-dev]. vgui-dev contain same data as from HLSDK, so it's all the same, just difference in download size.

Clone it somewhere and pass -DHL_SDK_DIR="path/to/repository".

**Comment by a1batross** [comment]
Thanks, I've fixed build manual. So it's more actual now. :)

**Comment by hpagseddy** [comment]
Now im gettin different error about fonts;
---log---

[ 30%] Building CXX object mainui/CMakeFiles/xashmenu.dir/font/BitmapFont.cpp.o
[ 31%] Building CXX object mainui/CMakeFiles/xashmenu.dir/font/FontManager.cpp.o
[ 31%] Building CXX object mainui/CMakeFiles/xashmenu.dir/font/FreeTypeFont.cpp.o
[ 32%] Building CXX object mainui/CMakeFiles/xashmenu.dir/font/StbFont.cpp.o
[ 32%] Building CXX object mainui/CMakeFiles/xashmenu.dir/font/BaseFontBackend.cpp.o
[ 33%] Linking CXX shared library libxashmenu.so
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../libfontconfig.so when searching for -lfontconfig
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libfontconfig.so when searching for -lfontconfig
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lfontconfig
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../libfreetype.so when searching for -lfreetype
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libfreetype.so when searching for -lfreetype
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lfreetype
collect2: error: ld returned 1 exit status
make[2]: *** [mainui/CMakeFiles/xashmenu.dir/build.make:1759: mainui/libxashmenu.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:86: mainui/CMakeFiles/xashmenu.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

---log---

**Comment by a1batross** [comment]
Install 32bit fontconfig & freetype, remove cmake cache ans try again.

**Comment by hpagseddy** [comment]
compiling succeed, this issue can close
