### ISSUE TITLE
Client.so error and not available playing

### ISSUE THREAD

**Issue by hpagseddy** [FWGS/xash3d#338]
Hi, i successfully compiled Xash3D but when i open it, it opens a client.so error and I cant select any map for playing. Menus are working, But Create server and Join server options are not available

**Comment by a1batross** [comment]
Which error? 

Run engine with "-dev 5 -log" and post an "engine.log" file here.

**Comment by hpagseddy** [comment]
[engine.log](https://github.com/FWGS/xash3d/files/1629541/engine.log)

**Comment by a1batross** [comment]
Well... What are you trying to do? You even don't have any files.

Download Half-Life files from Steam and use valve folder in Xash3D.

Counter-Strike doesn't work on PC platforms, because unimplemented
features. I don't plan to implement them.

14 янв. 2018 г. 7:50 ПП пользователь "Hpag Seddy" <notifications@github.com>
написал:

**Comment by hpagseddy** [comment]
I have valve folder in my Xash3D file

**Comment by hpagseddy** [comment]
Here's my Xash3D folder
---log---
engine.log  libvgui_support.so  libxashmenu.so  libxash.so  valve  vgui.so  xash3d  xash3d.sh
---log---

**Comment by hpagseddy** [comment]
Here's my Xash3D folder
---log---
engine.log  libvgui_support.so  libxashmenu.so  libxash.so  valve  vgui.so  xash3d  xash3d.sh
---log---

**Comment by a1batross** [comment]
So what? You're still missing the half of the game! I don't understand. If you are really a Gentoo user, you should know how to read logs, or at least you MUST know what means "No such file or directory" error.

**Comment by hpagseddy** [comment]
Yes i’ve read the log and i required someone’s opinion to agree it’s the problem. I’ll try with another valve folder tonight

**Comment by hpagseddy** [comment]
[engine.log](https://github.com/FWGS/xash3d/files/1632917/engine.log)
I tried a different valve folder and its still same, i cant enter on any map. Or creating a LAN server

**Comment by nekonomicon** [comment]
@hpagseddy, Do you have game libraries for linux( client.so and hl.so ) in cl_dlls and dlls folders?
Linux support for HL was added in 2013.
You must buy HL in steam or download game resources using steamcmd.
Another way: 
Build game libraries for HL using source code from [official repo](https://github.com/ValveSoftware/halflife) or [our repo](https://github.com/FWGS/hlsdk-xash3d).

**Comment by hpagseddy** [comment]
how can i build them @nekonomicon ?

**Comment by nekonomicon** [comment]
Read readme.md

**Comment by hpagseddy** [comment]
@nekonomicon i built it and copied to my Xash3D directory but still i cant create game. I put a log below
[engine.log](https://github.com/FWGS/xash3d/files/1635807/engine.log)

**Comment by nekonomicon** [comment]
Rename hl.so to hl_i386.so or edit gameinfo.txt.

**Comment by hpagseddy** [comment]
i solved it! i edited the gameinfo to hl.so and copied hl.so to valve/dlls folder
