### ISSUE TITLE
Rocket launcher bug in multiplayer

### ISSUE THREAD

**Issue by D0ve** [FWGS/xash3d#339]
Заметил один очень неудобный баг в мультиплеере (тестировал пока на андроид):
Когда стреляешь из ракетницы и свой красный огонёк наведения отключён, а у какого-нибудь другого игрока неподалёку  вкшючён,-    выпущенная ракета наводится по его(чужой т.е.) красной точке наведения(((, хотя должна лететь без наведения, ровно... .
Проверял на интернет-мультиплеере в андроид на последнем тестовом билде.

**Comment by FreeSlave** [comment]
Это не баг, а фича. Можно перенаправлять чужие ракеты. Такое поведение было в оригинальном Half-Life.

**Comment by nekonomicon** [comment]
Не баг.

**Comment by D0ve** [comment]
Тогда реально неудтбно((( т.е. чтобы попасть нужно включить свой целеуказатель(((, тогда уж лучше ещё и третий режим пожелать как в HL2 на захват цели после тайминга наведения))

**Comment by mittorn** [comment]
Ты это морпехам у которых гордон подобрал рпг скажи :)

**Comment by D0ve** [comment]
Вообще по идее раз valve придумала такой хинт со сбитием наведения ракеты, должен быть и антихинт, чтобы сбития прямой траектории не происходило, например зажимание при выстре кнопки 'использовать' !!! Типа Гордон пошаманил паяльником с электроникой армейского рпг)))

**Comment by mittorn** [comment]
Сложна. Гордон умеет только нажимать боьшие красные кнопки на которых написано "не нажимать"

**Comment by a1batross** [comment]
И двигать посторонние предметы в огромный научный прибор.

**Comment by D0ve** [comment]
Ну должен быть какой-нибудь антихинт всё-равно)) Хотя бы такой: нажал выстрел при включённом своём лазерном прицеле и тут-же его выключил- траекторию летящей ракеты уже сбить включённым другим прицелом нельзя))) типа уже запрограммил ракету)))

**Comment by mittorn** [comment]
Игра была выпущена в 1998 году и с тех пор изменяться она не будет. Всё.

**Comment by D0ve** [comment]
Вообще согласен, раз придумала так придумала.... .
    Но можно хотя бы ключ для консоли сделать чтобы у того кто бы его включил (т.е. выключил бы например "rpganitarget" в ''off'', ну как логический) траектория бы не сбивалась ? Ну а на серверах бы уже сами решали бы. Потому что хочу донести мысль))), - играть с этим вальвовским хинтом действительно аццки неудобно!!!  Вместо того, чтобы выстрелить и забыть, ракета летит чёрти знает куда.... . А если с лазерным прицелом стрелять тебя выносят пока держишь прицел !!!
Уважаемые отцы основатели, правда, идея с ключём имхо неплохая, кому нужно включили бы, а кому ненужно на серверах отключили бы.
Когда с рпг начинаешь баталию против десяти с рпг, - такой ключ увеличит геймплей в разЫ !!!
