### ISSUE TITLE
How can i install XashDS on Centos 7?

### ISSUE THREAD

**Issue by SinaloenseMx** [FWGS/xash3d#341]
How can i install XashDS on Centos 7?

I readed this https://github.com/FWGS/xash3d/wiki/How-to-set-up-a-Xash3D-Dedicated-Server-on-Debian-or-Ubuntu#todo

Is there a way to install repo in Centos 7?

**Comment by FreeSlave** [comment]
You can compile it yourself from https://github.com/FWGS/xash3d/tree/0.19.x branch enabling XASH_DEDICATED option via cmake.
Put the compiled binary to the same folder where valve and mods directories are located.
Use the full or relative path to the executable to run xashds.
You can also download a precompiled engine from here https://github.com/FWGS/xash3d-deploy and use its binary with -dedicated flag. But I'm not sure if travis builds are Centos 7 compatible.

**Comment by SinaloenseMx** [comment]
Thanks.
I tried with a precompiled engine from linux with this line:
`screen -S xashdscs ./xashds -game cstrike -port 27000 +maxplayers 32 +map de_dust2`

But I get these errors.

```
================================================================================
        Xash3D FWGS (build 731, Linux-i386) started at Jan17 2018 [14:03.41]
================================================================================
[14:03:41] execing config.cfg
[14:03:41] execing server.cfg
[14:03:41] execing banned.cfg
[14:03:41] execing listip.cfg
[14:03:41] Server logging data to file logs/L0117007.log
[14:03:41] L 01/17/2018 - 14:03:41: Log file started (file "logs/L0117007.log") (game "cstrike") (version "48/0.19/731")
[14:03:41] Server IP address: XXXXXXXXXX(MYIP <.<):27015
[14:03:41] SV_InitGame: can't initialize "dlls/cs.so":
dlls/cs.so: cannot open shared object file: No such file or directory
libstdc++.so.6: cannot open shared object file: No such file or directory
[14:03:41] Could not spawn server!
```

I have default dlls/cso.so

**Comment by FreeSlave** [comment]
Do you have 32-bit libstdc++ installed? Probably 
`yum install libstdc++.i686 # or dnf instead of yum`
will help.

**Comment by SinaloenseMx** [comment]
Thanks, I've been able to turn on the server and play.
But i have other problem.
When i start the server with line a line command, example:
`screen -S xashdscs ./xashds -game cstrike -port 27016 +maxplayers 32 +map cs_assault`
The server start with port 27015, and with the map de_dust2.

And server.cfg does not run when the server is started.

**Comment by SinaloenseMx** [comment]
Thanks, I opened a server and played.
But i have other problem.
I can´t set the port to server from line commands, i used this:
`screen -S xashdscs ./xashds -game cstrike -port 27016 +maxplayers 32 +map cs_assault`
And the server started with the port 27015.

**Comment by FreeSlave** [comment]
Set settings via server.cfg like here https://gist.github.com/a1batross/3ad52e7e335ef03772f5ac5c190a28dc
Btw the link to this gist is on the page you referenced in the first post.

xashds is not compatible with hlds in regard of command line options, yeah. Kinda inconvenient.

**Comment by SinaloenseMx** [comment]
Ok, very thanks! 👍
