### ISSUE TITLE
Баг с BloodSprite

### ISSUE THREAD

**Issue by vlad54rus** [FWGS/xash3d#352]
Если атакующий игрока противник находится вне поля зрения, то вылетающие частицы крови становятся белыми. Возможно есть и другие причины.
![q61ivvjc4a8](https://user-images.githubusercontent.com/22005398/36311533-7bab2016-1323-11e8-9404-d524381aae82.jpg)

**Comment by a1batross** [comment]
Не могу воспроизвести.

**Comment by vlad54rus** [comment]
Может быть оно зависит от чего то другого. Вот моё сохранение, включено бессмертие, и в меня стреляют два hgunt, на это раз я стою лицом к ним, и из меня летят белые частицы.
[quick.sav.zip](https://github.com/FWGS/xash3d/files/1733742/quick.sav.zip)

**Comment by a1batross** [comment]
Спасибо. Ошибка была для GLES платформ.

Исправил в 9c9e137031be529be64f9a086bb78faa4667f1ff


17 февраля 2018 г., 17:21 пользователь Vladislav <notifications@github.com>
написал:
