### ISSUE TITLE
Is is possible to set width/height and windowed/fullscreen via command line arguments?

### ISSUE THREAD

**Issue by x6herbius** [FWGS/xash3d#357]
I wrote this into my own fork (commits: [1](https://github.com/x6herbius/afterburner/commit/296d0bb3e6528b644c880d10581f20100b6f8847), [2](https://github.com/x6herbius/afterburner/commit/d51dd125cc256422ade8c321a98bd386b8c7b8c1)) because I couldn't find a nice way to do it at the time. If it's something that would be useful for the engine as a whole, I can clean it up and port it across in a pull request. The only minor conflict I can see is that we can't use `-h` to specify height (eg. like the Source engine does) because that's already used to display Xash's help.

**Comment by a1batross** [comment]
No, there is no way to do it. It would be nice to have such command line parameters. 

GoldSrc have -width, -height, -fullscreen and -windowed. With a bunch of aliases, like -w, -h, -full, -sw and so on, but I don't think they are necessary, as these four are most known.

**Comment by x6herbius** [comment]
OK cool, I'll look into doing that now.

**Comment by x6herbius** [comment]
Done - https://github.com/FWGS/xash3d/pull/359

**Comment by x6herbius** [comment]
All merged.
