### ISSUE TITLE
Compile using MSVC6

### ISSUE THREAD

**Issue by shefben** [FWGS/xash3d#363]
I don't know if this is just an issue i am having or if this is not compatible with vc6

but i get multiple errors when trying to compile it:

`client\cl_main.c(1698) : error C2143: syntax error : missing ';' before 'type'`
`client\cl_main.c(1708) : error C2065: 'extensions' : undeclared identifier`
`client\cl_main.c(1785) : error C2143: syntax error : missing ';' before 'type'`
`client\cl_main.c(1787) : error C2065: 'str' : undeclared identifier`
`client\cl_main.c(1885) : error C2061: syntax error : identifier 'CL_GetMessage'`
`client\cl_main.c(1885) : error C2059: syntax error : ';'`
`client\cl_main.c(1885) : error C2059: syntax error : 'type'`
`client\cl_main.c(1904) : warning C4013: 'CL_GetMessage' undefined; assuming extern returning int`
`server\sv_client.c(2200) : error C2143: syntax error : missing ';' before 'const'`
`server\sv_client.c(2203) : error C2065: 'model' : undeclared identifier`

**Comment by a1batross** [comment]
msvc6 build is not tested for engine.

I would recommend to use modern VC or just mingw.

**Comment by shefben** [comment]
sorry, i fixed the errors except for the cl_main.c errors, has something weird to do with
`		if(!CL_IsFromConnectingServer(from))
			return;`

**Comment by a1batross** [comment]
Nice to hear it. Can you send a PR with fixes? :)

**Comment by a1batross** [comment]
Fixed in 6a08c36e6f8331961aec38618a3a280f61ac3145.
