### ISSUE TITLE
flashlight problem

### ISSUE THREAD

**Issue by revelator** [FWGS/xash3d#365]
In some mods like blueshift the flashlight causes renderer smear when activated, does not happen on all maps but some so it might be related to what content is on the screen at the time.

**Comment by a1batross** [comment]
OS? Architecture? GPU? Version?

**Comment by revelator** [comment]
win 7 64 amd R9 390 version from git yesterday.

**Comment by revelator** [comment]
tried building with mingw64 32 bit and it works when built with that ??? some incompatibility with msvc 2015 maybe ?. Though i scratch my head as to why.

**Comment by a1batross** [comment]
Can you post a screenshot kf problem?

**Comment by a1batross** [comment]
Can you also enter "r_vbo 0" in console and switch flashlight again?

**Comment by revelator** [comment]
im having a tough time making a screenshot because it affects both the menu and the console so i cant see anything :/. Ill try turning vbo's off allthough it would be strange that it affects msvc 2015 and not mingw

**Comment by revelator** [comment]
Ok turning of vbo's seems to fix the problem, the mingw build also bugs out when it is on but more rarely.

**Comment by revelator** [comment]
Cannot play with vbo on so i have disabled it for the moment, usually indicates a broken pipeline somewhere, but in some cases its a bit more obscure. I have an engine that uses vertex arrays that exhibited much the same problem which turned out to be an AMD specific bug, in that case its easy to fix but if not it might take some time to hunt down.

**Comment by mittorn** [comment]
try r_vbo_dlightmode 1
It draws dlights different way, so maybe it fix rendering

**Comment by revelator** [comment]
Ah forgot to post back because of another bug that was caused by the same problem,
All works again.

**Comment by revelator** [comment]
Ouch seems this one is back again, latest pull from here same hardware.
r_vbo_dlightmode 1 does no difference this time.
