### ISSUE TITLE
Android axis inversion

### ISSUE THREAD

**Issue by meepingsnesroms** [FWGS/xash3d#369]
Please put it back, your not hosing the game files, there is no copyright violation and if there was distorting the gameplay would not protect you copyright charges.
This is April 1, but the google play release was made yesterday so I am assuming you are actually doing this, so if I am wrong please just tell me.

**Comment by mittorn** [comment]
host_nojoke 1

**Comment by meepingsnesroms** [comment]
It went away on its own after april 1 so no harm done, things like this give some variety to life.
