### ISSUE TITLE
Running a half-life expansion pack

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d#372]
How to run a half-life mod?

I have installed bshift mod, i copied bshift directory and put inside xash3d directory, next to the valve directory with half-life. Then, i opened a terminal and wrote "./xash3d -game bshift" without quotes. The game menu works but "New game", "Load Game" and "Multiplayer" options are not selectable.

**Comment by CitoplasmaX** [comment]
"Expansion pack" or "Mod" is mainly the same although depends of the game.

**Comment by CitoplasmaX** [comment]
http://www.indiedb.com/engines/xash3d-engine/features/running-half-life-under-xash3d-users-manual-english

I have followed this guide. Blue Shift depends of the main game.

**Comment by nekonomicon** [comment]
Half-Life was ported on linux in 2013. Blue shift too.
Check string "gamedll_linux" in your liblist.gam.

**Comment by JimSleezus** [comment]
Oh!! I've been using the Mac version of Half-Life.  Should it be the Windows or Linux version? :P

**Comment by CitoplasmaX** [comment]
nekonomicon: which liblist.gam? I have not idea what are you talking about.

**Comment by CitoplasmaX** [comment]
Okay it works but... "Multiplayer" option is not selectable yet... :(

**Comment by CitoplasmaX** [comment]
Okay i think it is normal. On liblist game shows single player only.

**Comment by CitoplasmaX** [comment]
Okay, the problem now is "gearbox" expansion, on his "dlls" directory does not exist a linux library version of "opfor.dll" and does not exist the same library on other directory.

**Comment by fuzun** [comment]
For blue shift;
https://github.com/malortie/halflife/tree/branch-malortie-bshift

**Comment by fuzun** [comment]
You need to look into the liblist.gam file and find the linux library in the Steam version of the game.

I mean if you can not or if you are not on PC, you can use malortie's open source ports instead and compile it yourself according to your needs.

https://github.com/malortie/halflife/tree/branch-malortie-op4

**Comment by nekonomicon** [comment]
@fuzun malortie's opposing force implementation not playable at all.
You can find reverse-engineered opposing force in this branch: https://github.com/H-I-N-G/hlsdk-xash3d/commits/opfor
Reverse-engineered blue shift here: https://github.com/nekonomicon/hlsdk-xash3d/tree/bshift

**Comment by CitoplasmaX** [comment]
echedey@echedey-500-500ns:~/Descargas/halflife-branch-malortie-op4/linux$ make
/bin/sh: 1: /valve/bin/g++-4.6: not found

Makefile specific errors ??? very bad

**Comment by CitoplasmaX** [comment]
echedey@echedey-500-500ns:~/Descargas/hlsdk-xash3d-opfor/build$ cmake ../
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at dlls/CMakeLists.txt:193 (add_library):
  Cannot find source file:

    gearbox/grapple_tonguetip.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: server
CMake Error: Cannot determine link language for target "server".
-- Generating done
-- Build files have been written to: /home/echedey/Descargas/hlsdk-xash3d-opfor/build

Really??

**Comment by FreeSlave** [comment]
H-I-N-G does not keep CMakeLists.txt actual. I think they use microndk and makefiles.
You can fix dlls/CMakeLists.txt yourself.

> Okay, the problem now is "gearbox" expansion, on his "dlls" directory does not exist a linux library version of "opfor.dll" and does not exist the same library on other expansion directory.

I don't see what you mean. Opposing Force from Steam definitely has opfor.so (which is linux library). I've never tested if it works with xash though.

**Comment by CitoplasmaX** [comment]
I have not the Steam version. I bought the expansion in a game market on my city some years ago.

**Comment by FreeSlave** [comment]
You can legally get game libraries for free and without having a steam account via [steamcmd](https://developer.valvesoftware.com/wiki/SteamCMD)

Example of usage:

`./steamcmd.sh +login anonymous +force_install_dir ./halflife +app_set_config 90 mod gearbox +app_update 90 validate +quit`

**Comment by CitoplasmaX** [comment]
It does not download opfor linux library.

**Comment by FreeSlave** [comment]
It should download all resources and libraries. Try running it again. Sometimes steamcmd does not download everything it should. Did you get halflife/gearbox directory at least?

**Comment by CitoplasmaX** [comment]
HLDS (appid 90) currently requires multiple runs of the app_update command before all the required files are successfully installed. Simply run app_update 90 validate multiple times until no more updates take place.

Okay it is a bug.

**Comment by CitoplasmaX** [comment]
It shows "Success! App '90' fully installed." and i don't see the opfor linux library on any directory.

**Comment by FreeSlave** [comment]
Libraries are located in gearbox/dlls and gearbox/cl_dlls. gearbox directory is located in whatever you passed as `force_install_dir`

**Comment by FreeSlave** [comment]
Maybe it needs an another run to get mod resources.

**Comment by nekonomicon** [comment]
>I have not the Steam version. I bought the expansion in a game market on my city some years ago.

You can use WON cd-key in steam to give half-life and all expansions for free.

**Comment by CitoplasmaX** [comment]
The cd-key was used years ago. I am currently required to pay

**Comment by CitoplasmaX** [comment]
And honestly, I step to install full steam for that. For this I play steam and now.

**Comment by nekonomicon** [comment]
Yet another solution( not panacea, but works ):
https://github.com/FWGS/xash3d/wiki/Building-and-running#using-dll-loader

**Comment by CitoplasmaX** [comment]
I think it would be better use the full windows build across wine.

**Comment by CitoplasmaX** [comment]
The windows build has some problems to solve. I will wait for an update to steam that i could download by steamcmd.

**Comment by necros2k7** [comment]
so any chance to run Blue shift with Xash3d?

**Comment by a1batross** [comment]
Just run it and it works.

**Comment by nekonomicon** [comment]
@necros2k7, Blue Shift retail release on linux?

**Comment by necros2k7** [comment]
win on win
