### ISSUE TITLE
CTD customize

### ISSUE THREAD

**Issue by AllanBoris** [FWGS/xash3d#378]
hi compiled xash3d fwgs
working better 1125
but now when after selection of character then press done - crash to desktop

**Comment by a1batross** [comment]
Ah, I know. It because menu is trying to save logo when it's not supported for old engine.

I need to add a check in mainui_cpp.

**Comment by a1batross** [comment]
https://github.com/FWGS/mainui_cpp/commit/4e80f07f0acc2ce2fb95a95c9ea67157b9dec859
