### ISSUE TITLE
[Feature Request] HTML In MOTD.

### ISSUE THREAD

**Issue by tyabus** [FWGS/xash3d#379]
Что еще сказать...

**Comment by nekonomicon** [comment]
HTML into GoldSource - vgui2 feature.
But vgui2 - closed-source and xash3d not supported it at all.

Needed simple HTML-parser.

**Comment by tyabus** [comment]
@nekonomicon https://github.com/hzqst/CaptionMod/tree/master/MetaHook/Plugins/CaptionMod
we can use this code,?

**Comment by tyabus** [comment]
@nekonomicon https://github.com/hzqst/CaptionMod/blob/master/MetaHook/Plugins/CaptionMod/vgui_controls/HTML.cpp

**Comment by nekonomicon** [comment]
Там только парсер csv.
А вобще в vgui2 просто интегрирован trident/cef. Так что даже при наличии открытой и легальной реализации толку от нее будет немного, cef конечно же открыт, но библиотека весит ~50мб.
Ну и motd с игровым движком не связан никак, это в sdk hl/cs нужно.

**Comment by a1batross** [comment]
Duplicate of #126.

**Comment by mittorn** [comment]
What features do you need for html? Maybe use some simple html render implementation?
Or implement markdown? It looks good even without render.
