### ISSUE TITLE
Mods don't work [iOS, 64 bit]

### ISSUE THREAD

**Issue by StevenSeiden** [FWGS/xash3d#389]
I have tried various mods, such as Opposing Force and Azure Sheep, and none of them seem to work.  I see them within the custom game section, but when I try to activate one, I get a grey screen, and the app crashes.

**Comment by mittorn** [comment]
Not engine issue, these mods are not availiable on ios.
Do not use custom game, launch with -game command-line option

**Comment by StevenSeiden** [comment]
Thank you!  That worked perfectly!

**Comment by ewewo2** [comment]
Hi, mods do Not work anymore (iOS 11.4.1 64 Bit), even cstrike 1.6.: Main Menu works, in Game crashes immediately. -game commandline option isnt Working too, half Life itself works perfectly but None of the mods does work. Is there any fix?

**Comment by mittorn** [comment]
cstrike will not work on 64 bit os, try other mods

**Comment by ewewo2** [comment]
Tried gunman, opposing forces, bot mod for hl and many others - none of them did work at all. 

Is this a Known issue?

Are there any plans to fix it or is it technically impossible?

Thanks

**Comment by nekonomicon** [comment]
>gunman
Gunman Chronicles has own game logic and working only on windows. This mod is closed source and impossible to port it on any alternative platform.

>opposing forces
Not ported on iOS  yet.

>bot mod
What is that? Any bot has own logic. How it must work on iOS.

>Is this a Known issue?
Not a bug.
You can't load x86 windows binaries on arm.

Check this [list](https://github.com/FWGS/xash3d/wiki/List-of-mods-which-work-on-Android-and-other-non-Windows-platforms-without-troubles) anyway.

**Comment by mittorn** [comment]
unpack ipa file and check server_xxx, client_xxx files, where xxx is gamedir
cstrike does not work, but all other mods that have this libraries should work.
You may also run mods based on spirit of half-life by setting library suffix to "sohl" (it overrides gamedir)
