### ISSUE TITLE
How to make a static build?

### ISSUE THREAD

**Issue by CrusoeDaWolf** [FWGS/xash3d#393]
It seems like using -DXASH_STATIC doesn't make a static build of the engine.
Launching HL gives me a missing library error (libxashmenu) and I kinda expected a binary larger than 2 megabytes.

**Comment by Mr0maks** [comment]
@CrusoeDaWolf , -DXASH_STATIC=1

**Comment by nekonomicon** [comment]
This option will create one big binary using code from launcher, engine and loader folders. Nothing more. Mainui will be as separate library anyway.

**Comment by CrusoeDaWolf** [comment]
Why exactly is MainUI serparate though? Seems like an odd decision for a 'static' build.

**Comment by a1batross** [comment]
>gives me a missing library error

man LD_LIBRARY_PATH

Fully static builds are not supported anyway.

**Comment by mittorn** [comment]
static binary cannot load dynamic libraries. It useful only with dll loader. We do not have own elf loader
xashds-android x86 binary built with this options:
```
make -f Makefile.linux XASH_STATIC=1 XASH_DLL_LOADER=1 XASH_DEDICATED=1
```
