### ISSUE TITLE
Having trouble trying to map SteelSeries Stratus bluetooth controller on iOS

### ISSUE THREAD

**Issue by CyanFireUK** [FWGS/xash3d#400]
It might be me being stupid but i cannot figure out how to make this controller work in game, if anyone has any tips or can help that would be great! I'm non-jb.

**Comment by a1batross** [comment]
Try to use "-sdl_joy_old_api" command line switch. It enables raw game controller access. It may be incompatible with some controllers, but may work in youe case.

**Comment by CyanFireUK** [comment]
Yes! it now recognises my controller, only problem now is the camera is spinning round & round in circles

**Comment by a1batross** [comment]
You may remap triggers in Gamepad menu.

**Comment by CyanFireUK** [comment]
Thankyou for your help! Nearly have my controller fully working, i can’t seem to map my B button however. Since it’s the back button for the menu when i have a binding highlighted & it says press a key when i press B on my controller it just jumps back to the control menu instead & doesn’t assign B_BUTTON to the binding i want (duck)

**Comment by a1batross** [comment]
It's known bug of menu, you may bind it from console instead. 

DPad should be identified as arrow keys, try to rebind them in menu.

**Comment by CyanFireUK** [comment]
What would the console command be? I have got as far as: bind B_BUTTON

**Comment by florin-pop** [comment]
@CyanFireUK do you remember what the fix was to stop the camera from spinning around?
