### ISSUE TITLE
Hidden flashlight & settings touch overlay buttons re-appear when re-entering game (iOS)

### ISSUE THREAD

**Issue by CyanFireUK** [FWGS/xash3d#401]
The flashlight & settings buttons for the touch overlay re-appear when you re-enter the game on iOS if they've been hidden previously, the settings for these buttons don't save

**Comment by nekonomicon** [comment]
Press `done` in the settings and `quit` in the main menu.

**Comment by CyanFireUK** [comment]
They still re-appear after launching the game again

**Comment by nekonomicon** [comment]
Try create new touch profile.

**Comment by CyanFireUK** [comment]
I cannot create a new touch profile, i name it and save it but it doesn’t get created. I’m non-jb if that can cause issues

**Comment by a1batross** [comment]
As old engine may NOT receive updates anymore, please take a look at this issue in new engine repo.

https://github.com/FWGS/xash3d-fwgs/issues/61

I will close this, as no bugfix in both engine branches will be added, until someone else will become OSX/iOS maintainer and finally fix it.
