### ISSUE TITLE
Can't climb ladders with mapped Bluetooth controller on iOS

### ISSUE THREAD

**Issue by CyanFireUK** [FWGS/xash3d#402]
I have just discovered after finally mapping my bluetooth controller to work fully that i am unable to climb up and down ladders, is there a way to fix this?

**Comment by a1batross** [comment]
What you use for moving? Sticks? D-Pads? Maybe buttons?

**Comment by CyanFireUK** [comment]
I’m using sticks for movement

**Comment by a1batross** [comment]
Okay. Enter cl_showpos 1 in console and say on which velocity you are moving. Maybe I need to add scaling for stick values.

**Comment by CyanFireUK** [comment]
I am moving forward & back at a velocity of about 200

**Comment by a1batross** [comment]
Nice! I will implememt scaling then. :)

In fact, your controller should return values from -32768 to 32767 per axis. But seems that it return a bit lower, so you don't have enough velocity to climb up a ladders.

**Comment by CyanFireUK** [comment]
I have the sliders turned down to about half way, turning them back up allowed me to climb ladders again. I report a velocity of 320 with the sliders up. I have them down for a slower run speed.

**Comment by CyanFireUK** [comment]
I’ve played Half Life countless times and never noticed that haha!

**Comment by a1batross** [comment]
As old engine may NOT receive updates anymore, please take a look at this issue in new engine repo.

https://github.com/FWGS/xash3d-fwgs/issues/61

I will close this, as no bugfix in both engine branches will be added, until someone else will become OSX/iOS maintainer and finally fix it.
