### ISSUE TITLE
iOS: cannot return back after opening console

### ISSUE THREAD

**Issue by MoeMod** [FWGS/xash3d#412]
iOS devices dont have any return button or esc key,
so that the console cannot be closed.

copied from https://github.com/mittorn/xash3d-ios/issues/2

**Comment by a1batross** [comment]
There a small zone on bottom left corner. Try it.

**Comment by MoeMod** [comment]
Found it! Wow!
It's really confusing...

**Comment by a1batross** [comment]
Also, you can enter "toggleconsole" in console, it will close it.
