### ISSUE TITLE
install_fs: Function not implemented Couldn't install fs segment, expect segfault

### ISSUE THREAD

**Issue by Myrkonianin** [FWGS/xash3d#419]
I got this error, after i run xash3d.sh. I running on fresh-installed archlinux x64.

**Comment by a1batross** [comment]
@mittorn 

Looks it's dll loader issue. How we should workaround that?

**Comment by mittorn** [comment]
Build latest engine from source or enable CONFIG_MODIFY_LDT_SYSCALL in kernel

**Comment by mittorn** [comment]
https://github.com/FWGS/xash3d/commit/15be0a7082a7b532814b0e7dbe28b963236c9efa#diff-3decf9ca5c4f15661febc04f2fce0cf7
