### ISSUE TITLE
[delete]

### ISSUE THREAD

**Issue by necros2k7** [FWGS/xash3d#425]
subj

**Comment by a1batross** [comment]
Use TGA for that.

GIMP for example can generate TGA with RLE.

**Comment by necros2k7** [comment]
you mean i can just simply convert for example valve\gfx\shell\btns_main to TGA and engine will run fine?

**Comment by mittorn** [comment]
yes, it already converted in xash-extras

**Comment by a1batross** [comment]
MP3 is already compressed enough. You can use MP3 instead of WAV files. 

However, OPUS will be supported, because voice chat.

MP4 is just a container, as well as AVI.

**Comment by necros2k7** [comment]
how can i use mp3 instead of wav? tried to convert 1st dialogue in train to mp3, renamed mp3 to wav - still silence in game when dialogue should be

**Comment by necros2k7** [comment]
what so funny, who knows how engine reads these files by content/extension
stil no luck 1. c0a0_tr_gmorn.mp3 2. c0a0_tr_gmorn.wav (mp3 inside)
"MP3 is already compressed enough. You can use MP3 instead of WAV files."

**Comment by nekonomicon** [comment]
Lol. You must change file extensions into engine and sdk. Engine will detect file format by extension.

**Comment by lewa-j** [comment]
> who knows how engine reads these files

The one who saw the code.
https://github.com/FWGS/xash3d/blob/ab7c3848f85571a3f86817a2ced3fb87371ea560/engine/common/soundlib/snd_main.c#L75
https://github.com/FWGS/xash3d/blob/ab7c3848f85571a3f86817a2ced3fb87371ea560/engine/common/soundlib/snd_utils.c#L33

**Comment by necros2k7** [comment]
ok, thanx now i see , just thought binaries in Release section supported wav and mp3 already
