### ISSUE TITLE
Invalid signature on iOS

### ISSUE THREAD

**Issue by StevenSeiden** [FWGS/xash3d#431]
The signature for the current .ipas available appears to no longer be valid.  Installing the application with Cydia Impactor fails on multiple devices.

**Comment by mittorn** [comment]
Resign it. We do not have valid signatures

**Comment by mittorn** [comment]
unpack ipa, codesing xash all client, server, menu files, pack it to zip again and codesign archive

**Comment by StevenSeiden** [comment]
It appears that some sort of new ipa integrity verification is in place on macOS.  However, this does not affect the Windows version of Impactor.  In the end I was able to install the ipa properly using Cydia Impactor and Windows 10.
