### ISSUE TITLE
SYS Crash

### ISSUE THREAD

**Issue by Vokuar** [FWGS/xash3d#432]
i keep getting this error with sven coop
i am running the windows build
any help would be appreciated

![image](https://user-images.githubusercontent.com/23405516/50051144-bcee6280-0158-11e9-871a-c538957dc5a5.png)

**Comment by nekonomicon** [comment]
Which sven coop version?
Sven coop 5.0+ uses undocumented features and does not work under Xash3D and Xash3D FWGS at all.

**Comment by Vokuar** [comment]
i tried 4.8 and 5.0 with 5.0 not working at all

**Comment by Vokuar** [comment]
4.8 crashing and thats when i got syscrash

**Comment by Vokuar** [comment]
okay so interestingly enough 3.0 works fine
