### ISSUE TITLE
Hostage AI didn't seem to work unlike in CSMoE mod. 

### ISSUE THREAD

**Issue by sledgehammer0019** [FWGS/xash3d#442]

**Comment by a1batross** [comment]
Can you describe? It's probably not an engine issue.

**Comment by sledgehammer0019** [comment]
I don't really know if it's an engine issue (or not). In CSMoE (created by Moe) mod (in Android) the hostages functions like the one in CSCZ were they shout for you, and they react when you bump them or shoot near them. I downloaded a CSCZ Hostage AI mod for CS 1.6 and I installed it in the directory but nothing happens, except that you can call the hostages even in far directions. I just hope that hostages might function because it adds realism to the game! Thank you!

**Comment by sledgehammer0019** [comment]
I don't really know if it's an engine issue (or not). In CSMoE (created by Moe) mod (in Android) the hostages functions like the one in CSCZ were they shout for you, and they react when you bump them or shoot near them. I downloaded a CSCZ Hostage AI mod for CS 1.6 and I installed it in the directory but nothing happens, except that you can call the hostages even in far directions. I just hope that hostages might function because it adds realism to the game! Thank you!

**Comment by a1batross** [comment]
Hostage AI implemented in game code, so you can't really change their behaviour just by copying some probably malicious files. Reason is the same why you can't run AMXModX and so on, but CSMoE have modified game code, so you have zombies, new weapons, new HUD and other things here.

But you can play CZero then. Tap numerous times on app icon in CS16Client and you will see a new button under the "Enable ZBot bots", which enables czero. **THIS IS UNSUPPORTED YET, I WILL NOT ACCEPT ANY BUGREPORTS ON THIS!**
