### ISSUE TITLE
Latest build ios 12 - shouldn't be file system case-insensitive?

### ISSUE THREAD

**Issue by TuTuc0** [FWGS/xash3d#450]
I have noticed that files system is case sensitive, engine couldn't find some models/sprites such as w_9mmar.mdl, however renaming these to w_9mmAR.mdl etc. will make it appear in game.

It is possible to use -casesensitive in commandline, so I suppose it should be insensitive by default?

**Comment by MoeMod** [comment]
If we changelevel DE_DUST2, for example, it works fine to find de_dust2.bsp.
However, when clients with de_dust2.bsp connects to the server, it results in error that DE_DUST2.bsp not found.
Tested with macOS server and iOS client.

**Comment by mittorn** [comment]
It is because old osx/ios versions was case insensitive by default and we disabled code that handled it to improve performance

**Comment by mittorn** [comment]
https://github.com/FWGS/xash3d/blob/master/engine/common/filesystem.c#L319

**Comment by MoeMod** [comment]
It seems that filesystem on iOS simulator is case-insensitive while the one on real devices is case-sensitive

**Comment by mittorn** [comment]
No, i tested on real device with ios8. It was changed in 11 or 12
And simulator uses host fs. it just library which implements ios api and shows ios screen on mac

**Comment by a1batross** [comment]
As old engine may NOT receive updates anymore, please take a look at this issue in new engine repo.

https://github.com/FWGS/xash3d-fwgs/issues/61

I will close this, as no bugfix in both engine branches will be added, until someone else will become OSX/iOS maintainer and finally fix it.
