### ISSUE TITLE
Remove bunnyhop speedcap for half-life

### ISSUE THREAD

**Issue by yosoynacho** [FWGS/xash3d#455]
I would be cool to have this on singleplayer and hldm

**Comment by nekonomicon** [comment]
It's not engine feature.
Bhopcap was added in HLSDK.
Our [HLSDK](https://github.com/FWGS/hlsdk-xash3d) fork already has mp_bhopcap cvar to avoid bhopcap.

**Comment by yosoynacho** [comment]
oh i see... didn't know
