### ISSUE TITLE
Can't build or even use precompiled release on MX Linux/Debian (64-bit)

### ISSUE THREAD

**Issue by jones137** [FWGS/xash3d#458]
If I try to run executable:

> ./xash3d: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory

If I try to compile after installing cmake ; gcc-multilib ; libstdc++6:i386

> The output was:
> 1
> /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/libstdc++.so when searching for -lstdc++
> /usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/6/libstdc++.a when searching for -lstdc++
> /usr/bin/ld: cannot find -lstdc++
> collect2: error: ld returned 1 exit status

Would be very appreciated if you released a Flatpak version, then there won't be problems with libraries on Linux.

**Comment by a1batross** [comment]
Did you tried to install g++-multilib and libstdc++-dev:i386 also?

If you're struggling with building, there is an autobuilds in `xash3d-deploy` repository.

As you've mentioned Flatpak, we're also testing AppImage-based approach for the new fork, so try it. It needs only i386 libc and libstdc++ for your system, but I'm searching for a portable solution to get rid of this external dependency.

**Comment by jones137** [comment]
I can't even run AppImage

> $ ./Xash3DFWGS-i386.AppImage 
Xash3D FWGS installed as AppImage.
/tmp/.mount_Xash3Dc3Mla7/AppRun: 6: [: unexpected operator
/tmp/.mount_Xash3Dc3Mla7/AppRun: 11: /tmp/.mount_Xash3Dc3Mla7/AppRun: /tmp/.mount_Xash3Dc3Mla7/xash3d: not found

but I guess this is a different kind of issue for different repo.

**Comment by a1batross** [comment]
I've fixed this issue, try again.
