### ISSUE TITLE
Instead of G-Man stands scientist on the map c1a0

### ISSUE THREAD

**Issue by VladAndroidGamer** [FWGS/xash3d#459]
In Xash3D FWGS Test 0.19.3 Android version (travis-master branch) There is this bug:
![Screenshot_2019-07-06-15-29-24-398_in celest xash3d hl test](https://user-images.githubusercontent.com/22411953/60758737-8583cc80-a03c-11e9-9536-3092cdf3ac70.png)

Баг на тестовой версии движка, вместо G-Man'а стоит учёный на карте c1a0

На релизной версии в Play Маркете такого нет

**Comment by nekonomicon** [comment]
У меня с оригинальными ресурсами подобного бага нет, но при выходе из игры происходит вылет в filesystem.c на строчке 2534.
Вероятно, китаец что-то сломал.

**Comment by VladAndroidGamer** [comment]
Понял, проблема была в файле c1a0.ent. Я его удалил
