### ISSUE TITLE
VBO Renderer working strange

### ISSUE THREAD

**Issue by tyabus** [FWGS/xash3d#460]
I have discovered that vbo renderer working strange, because i can't belive that my device can't handle half-life. It drops fps on: particles, sprites, randomly.
![Screenshot_20190728-191032_Xash3D_FWGS](https://user-images.githubusercontent.com/19637128/62007161-fc0f7800-b16b-11e9-814e-668da57b4992.png)
Here is the r_info.

**Comment by a1batross** [comment]
VBO renderer includes only world rendering.

Contact your manufacturer about GLES1 drivers performance.

**Comment by tyabus** [comment]
> VBO renderer includes only world rendering.
> 
> Contact your manufacturer about GLES1 drivers performance.

I have uninstalled gltools (and module for magisk) , problem seems to be solved.

**Comment by mittorn** [comment]
Contact gltools developer, it should not drop performance with all features disabled
