### ISSUE TITLE
Как использовать на сервере кастомные карты?

### ISSUE THREAD

**Issue by mfi01** [FWGS/xash3d#463]
Как использовать на xashDS сервере кастомные карты?

**Comment by a1batross** [comment]
Берёшь и используешь. Доставку до клиента можно и нужно через FastDL настроить, это делается ровно точно так же, как в GoldSrc. За исключением sv_allowdownload. В GoldSrc он называется sv_allowdownload, у нас sv_allow_download.

**Comment by mfi01** [comment]
Host_Error: Map Design Error: Mod_ForName: maps/test.bsp unkown format

**Comment by a1batross** [comment]
В тексте ошибки написано что с файлом не так.
