### ISSUE TITLE
build number

### ISSUE THREAD

**Issue by AndrewOculus** [FWGS/xash3d#468]
Hello! What is the build number - Xash3D FWGS (build 1747, Linux-i386) - 1747? when I do the build on my own then the build number is 1747, but when I use release from https://github.com/FWGS/xash3d/releases (xash3d_fwgs_linux_0.19.2.tar.xz) the build number is 1200. My build crashes after connecting metamod but release build works nice. My system is ubuntu 18.04, cmake 2.8.12 , for building use "cmake -DHL_SDK_DIR=../hlsdk -DXASH_DEDICATED=YES -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_EXE_LINKER_FLAGS="-m32" ../ && make".

**Comment by nekonomicon** [comment]
It's outdated version.
Please use the latest version from here:
https://github.com/FWGS/xash3d-fwgs

>What is the build number - Xash3D FWGS (build 1747, Linux-i386) - 1747?

Count of days from first release date(1 April 2015)

**Comment by nekonomicon** [comment]
Also, you need to use metamod from here:
https://github.com/mittorn/metamod-p

**Comment by AndrewOculus** [comment]
I know that this is old code, I tried to use the new code but it does not work either. Server freezes at word: [17:31:36] type 'map <mapname>' to run server... (TAB-autocomplete is working too)
For build I use "./waf configure -T release -d --prefix=/home/computer/workspace/xash-build"

**Comment by AndrewOculus** [comment]
So I use already builded metamod from https://www.moddb.com/engines/xash3d-fwgs-engine/downloads/metamod-p-121p37-custom-build-for-xash3d

**Comment by AndrewOculus** [comment]
when i type 'map <mapname>' to run server nothing happens ((

**Comment by AndrewOculus** [comment]
then I rebuild metamod it crash on amx mod x : "Crash: signal 11 errno 0 with code 1 at 0xf4d05300 (nil)
Stack backtrace:
 1: 0xf5296400 (/home/computer/workspace/Half-Life/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so)
 1: 0xf5296400 (/home/computer/workspace/Half-Life/cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so)"
