### ISSUE TITLE
Error: pfnWriteString: exceeds 234 symbols

### ISSUE THREAD

**Issue by Severin228** [FWGS/xash3d#469]
Постоянно выскакивает эта ошибка, засоряет все и падает сервер.

**Comment by a1batross** [comment]
Поддержка старого движка подходит к концу и в нём никаких изменений проводиться не будет.

**Comment by a1batross** [comment]
Как вариант -- найти что вызывает pfnWriteString и сделать так, чтобы оно не переполняло буфер.

**Comment by Severin228** [comment]
> Да, но я даже плагины отключал.
Ошибка все равно буфер засоряет..

**Comment by a1batross** [comment]
Можешь подправить исходный код и сделать чтобы это было некритичной ошибкой. 

Голдсорс все равно обрезает, просто делает это молча.

**Comment by Severin228** [comment]
А где можно подправить его, в каком исходнике?

**Comment by lewa-j** [comment]
https://github.com/FWGS/xash3d/blob/725fd84b5ba8d405979d63df7a906feb1bc87d51/engine/server/sv_game.c#L2783

**Comment by Severin228** [comment]
У меня таких папок нет.

**Comment by Severin228** [comment]
Есть кеш: 
cstrike
valve
Файл,через что производится запуск сервера:
start.sh

**Comment by Severin228** [comment]
Ну и addons, где лежит сам metamod и AmxModX

**Comment by Severin228** [comment]
Просто сервер cs
