### ISSUE TITLE
Hey bro.Do you know what happened to this?

### ISSUE THREAD

**Issue by SuperRock2099** [FWGS/xash3d#470]
We have just complied xash3d and cs16client and then we edited it,but we don't know why the decals just arrange orderly.Just like the picture below:
http://m.qpic.cn/psc?/V10hSPmr0j72wm/h4SLI6MeeCc7mRdKk01ustKtjdQ3mVxIMaiMewtG2i21qc4cZjaf63KQz.i**ZkB2YeXdX1ddzVQ8WwVXN7SUO2T9YMddghNOShn7d7OrF0!/b&bo=1Ag4BAAAAAARB9A!&rf=viewer_4
DO YOU KNOW WHY?WE REALLY WANT TO SOLVE THIS PROBLEM!

**Comment by a1batross** [comment]
We don't provide any support for old engine and cs16client.

**Comment by SuperRock2099** [comment]
but this is new xash3d :(

**Comment by mittorn** [comment]
4.2

**Comment by SuperRock2099** [comment]
what？

**Comment by mittorn** [comment]
cs16client does not work with new xash3d
