### ISSUE TITLE
Chrome textures on models not lit by dynamic lights

### ISSUE THREAD

**Issue by UCyborg** [FWGS/xash3d#79]
![c1a1f_shot0000](https://cloud.githubusercontent.com/assets/3683626/10635725/28a20ff8-77fb-11e5-87b1-af3cfbdb68c8.png)
![c3a2_shot0000](https://cloud.githubusercontent.com/assets/3683626/10635978/c3e7e7f2-77fc-11e5-934a-35686d930c51.png)

**Comment by a1batross** [comment]
Not a bug anymore, as new engine does not support per-vertex light on studio models.
