### ISSUE TITLE
Android navigation bar

### ISSUE THREAD

**Issue by SteveAdams86** [FWGS/xash3d#99]
On certain devices such as the Google nexuses there is no hardware keys and when playing games using xash the navigation keys are always visible. If I try to hide the navigation bar the view gets all messed up. This is going to be harder to explain than I try to care to even attempt so here I leave a link to my Google drive showing what it looks like. 2 screen shots playing the game 'normally' and 2 when I try to hide the navigation bar so I can use all my screen https://drive.google.com/folder/d/0B2ar5BB6clkDX1ZIdEhxZ0Jvdkk/edit

**Comment by a1batross** [comment]
You shouldn't hide navbar. How you will open menu without back key?

**Comment by SteveAdams86** [comment]
On other apps where the bar is hiden touching the screen on the status bar area or swiping in from the nav bar would be reveals it for a few seconds and then it hides again. On devices such as nexus without the hardware keys it makes applications much more enjoyable to use all of the screen

**Comment by SteveAdams86** [comment]
I have uploaded a couple more screen shots from another game into the game album from the link above to show you how it looks hiding the navigation bar and another screen shot with the navigation bar and status bar revealed

**Comment by Bacte** [comment]
It's called "immersive mode". Such feature is common in modern apps. Playing in "real" full screen would be really nice, I definitely vote for this.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-android-project/commit/8133cd9d01bf9545864212a28b83c28c2c6fc7e8

Fixed. Only for 4.4 and higher.
